### ISSUE TITLE
Unable to build sdk for android.

### ISSUE THREAD

**Issue by ankurgamedev** [aws/aws-sdk-cpp#2509] opened 2023-05-24 04:54 UTC
### Describe the bug

We are also facing the same issue sdk compiling fine for win and linux.But for android we are helpless.

Command : cmake ../aws-sdk-cpp -DENABLE_UNITY_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DTARGET_ARCH=ANDROID -DCUSTOM_MEMORY_MANAGEMENT=ON -DANDROID_NATIVE_API_LEVEL=19 -DNDK_DIR="/home/ankur/Android/Sdk/ndk/19.2.5345600" -DENABLE_TESTING=OFF -DCMAKE_PREFIX_PATH=/usr/local/install_sdk_android  -DCMAKE_INSTALL_PREFIX=/usr/local/install_sdk_android -DBUILD_ONLY="apigateway;apigatewayv2;apigatewaymanagementapi;appsync;chime;cognito-identity;cognito-idp;cognito-sync;connect;dax;docdb;dynamodb;ec2;ecr;ecs;elasticache;email;eventbridge;events;iam;identity-management;lambda;mediaconnect;mediaconvert;medialive;mobile;pinpoint;queues;rds;s3;sesv2;sms;sms-voice;sqs;ssm"

--   Building Curl as part of AWS SDK
CMake Error: The source directory "/home/<user>/AWS/aws-sdk-cpp/android-build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake Error at cmake/build_external.cmake:139 (message):
  Failed to configure dependency libraries.
Call Stack (most recent call first):
  CMakeLists.txt:198 (include)

### Expected Behavior

Static Libs for android.

### Current Behavior

Not able for build aws sdk c ++ for android target

### Reproduction Steps

cmake ../aws-sdk-cpp -DENABLE_UNITY_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DTARGET_ARCH=ANDROID -DCUSTOM_MEMORY_MANAGEMENT=ON -DANDROID_NATIVE_API_LEVEL=19 -DNDK_DIR="/home/ankur/Android/Sdk/ndk/19.2.5345600" -DENABLE_TESTING=OFF -DCMAKE_PREFIX_PATH=/usr/local/install_sdk_android  -DCMAKE_INSTALL_PREFIX=/usr/local/install_sdk_android -DBUILD_ONLY="apigateway;apigatewayv2;apigatewaymanagementapi;appsync;chime;cognito-identity;cognito-idp;cognito-sync;connect;dax;docdb;dynamodb;ec2;ecr;ecs;elasticache;email;eventbridge;events;iam;identity-management;lambda;mediaconnect;mediaconvert;medialive;mobile;pinpoint;queues;rds;s3;sesv2;sms;sms-voice;sqs;ssm"

### Additional Information/Context

I

### AWS CPP SDK version used

Latest github source at 

### Compiler and Version used

clang

### Operating System and version

Ubuntu 22.04

**Comment by yasminetalby** [comment] 2023-05-24 16:27
Hello @ankurgamedev ,

Thank you very much for your submission.
This issue has already been brought up to the team and is a duplicate of the following issue submission : https://github.com/aws/aws-sdk-cpp/issues/2452
I see that you have commented there. To help with issue tracking, I was wondering if I could close this submission as a duplicate and post updates and communications on the original submission. You will be notified as you have commented there as well.

Thank you very much for your time and collaboration.

Sincerely,

Yasmine

**Closed** 2023-05-24 18:25 UTC
Labels: bug, duplicate, response-requested

**Comment by ankurgamedev** [comment] 2023-05-24 18:26
But please resolve the issue as We are unable to use latest version of sdk within our game. Version 1.8 is compiling.
