### ISSUE TITLE
Break out major minor release parts of version

### ISSUE THREAD

**Issue by DennisHeimbigner** [aws/aws-sdk-cpp#1615] opened 2021-04-12 18:52 UTC
Since version 1.8 breaks some version 1.7 code (e.g. followRedirects)
I need a way to test the major+minor version numbers in my code.
Please consider adding something like this to VersionConfig.h(.in).
````
#define AWS_SDK_VERSION_STRING "1.7.364"
#define AWS_SDK_VERSION_MAJOR 1
#define AWS_SDK_VERSION_MINOR 7
#define AWS_SDK_VERSION_RELEASE 364
````
Not that the values should be integers not strings.

**Comment by KaibaLopez** [comment] 2021-04-12 22:42
Hi @DennisHeimbigner ,
We have an open FR on this subject [here](https://github.com/aws/aws-sdk-cpp/issues/1472). 
Is this the case for you as well? Or could you use the `Aws::Version::GetVersionMajor()` / `Aws::Version::GetVersionMinor() `/ `Aws::Version::GetVersionPatch()` from `aws/core/Version.h`?

**Comment by DennisHeimbigner** [comment] 2021-04-12 23:09
No. For us the tests have to be in the C preprocessor so they need to be macros.
The problem is that we need to choose between these two lines:
1. config->followRedirects = true
2. config->followRedirects = DEFAULT

and I can see no way to do this at run time without causing an error on the line not chosen

**Comment by KaibaLopez** [comment] 2021-04-12 23:46
hmm, can you give me a sample on what you're trying to do, like a small standalone code sample? To me it sounds like this could be done the way you described it :
```cpp
if(Aws::Version::GetVersionMinor() >= 7)
      clientConfig->followRedirects = Aws::Client::FollowRedirectsPolicy::DEFAULT;
else
      clientConfig->followRedirects = Aws::Client::FollowRedirectsPolicy::ALWAYS;

 ```

 But if you need this to be defines then I'd say this is a duplicate of the issue I linked.

**Comment by DennisHeimbigner** [comment] 2021-04-13 01:35
Yes, this is the same problem as the linked issue.

**Comment by KaibaLopez** [comment] 2021-04-28 18:38
Hi, 
This has now been merged and the Major/Minor and Patch Versions are exposed as defines.

**Closed by KaibaLopez** 2021-04-28 18:38 UTC
Labels: feature-request
