### ISSUE TITLE
compilation of EC2Client.cpp fails "c++: internal compiler error: Killed (program cc1plus)"

### ISSUE THREAD

**Issue by tinkyholloway** [aws/aws-sdk-cpp#496] opened 2017-04-12 08:13 UTC
This is probably the wrong place for this issue, but perhaps someone has experience...

`$ git clone --branch 1.0.103 https://github.com/aws/aws-sdk-cpp.git`

`$ cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_RTTI=ON -DENABLE_TESTING=OFF -DMINIMIZE_SIZE=OFF -DCMAKE_BUILD_TYPE=Release ..`

(also tried MINIMIZE_SIZE=ON)

```
$ /usr/bin/c++   -DENABLE_CURL_CLIENT -DENABLE_OPENSSL_ENCRYPTION -DPLATFORM_LINUX @CMakeFiles/aws-cpp-sdk-ec2.dir/includes_CXX.rsp -Wall -Werror -pedantic -Wextra -fno-exceptions -fPIC -O3  -DNDEBUG   -std=c++11 -o CMakeFiles/aws-cpp-sdk-ec2.dir/source/EC2Client.cpp.o -c /root/build/aws-sdk-cpp/aws-cpp-sdk-ec2/source/EC2Client.cpp
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
```

I've tried mucking about with different optimisation levels.

```
$ ulimit -s
16384

$ uname -a
Linux odroid 3.10.96-113 #1 SMP PREEMPT Wed Jul 6 22:19:28 UTC 2016 armv7l armv7l armv7l GNU/Linux

$ /usr/bin/c++ --version
c++ (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by JonathanHenson** [comment] 2017-04-14 01:37
You need 4 gigs of ram to link EC2 on GCC. Unfortunately, there isn't much we can do about it (it's a massive API). If you really need it at the moment, you can try deleting operations you don't want.

**Comment by Bu11etmagnet** [comment] 2017-04-19 11:14
You need a 64-bit GCC to compile EC2. A 32-bit GCC can't allocate enough memory. See #133 (this is probably a duplicate of it)

**Closed** 2017-04-20 08:41 UTC
Labels: help wanted
