### ISSUE TITLE
Crash in function Aws::Monitoring::GetHttpClientMetricNameByType

### ISSUE THREAD

**Issue by nguoithichkhampha** [aws/aws-sdk-cpp#1099] opened 2019-03-25 10:07 UTC
### What platform/OS are you using?
Mac OS X 10.13.3
### What compiler are you using? what version?
clang
### Can you provide a TRACE level log? (sanitize any sensitive information)
[trace_sync1.txt](https://github.com/aws/aws-sdk-cpp/files/3002669/trace_sync1.txt)

We are facing with crash issue. Please take a look in the stack trace. I'm not sure the bug from your side or something wrong when we implement aws-sdk.
We are using version 1.7.71

**Comment by nguoithichkhampha** [comment] 2019-03-25 11:04
from stack trace. it crash in this function
auto it = metricsTypeToName.find(static_cast<int>(type));
I'm thinking function find() of static map is not thread safe.

**Comment by singku** [comment] 2019-03-25 19:13
STL map spec doesn't guarantee thread safety of `find`. But the general sense of find is just `reading` information for the tree. So I think most  probably it's thread safe for concurrent readers. The only problem I see from here is concurrent calls to that function. One thread is initializing the map during first call and another thread call that function during the initialization. Could you please give more information about your use case or your sample code? Or could you please verify this is the root cause?

**Comment by nguoithichkhampha** [comment] 2019-03-26 03:44
Yes, I tried to move static map outside the scope of functions and seems it's not crash. I'm waiting response from our QA and will send you the result soon.

**Comment by nguoithichkhampha** [comment] 2019-03-27 09:51
Update, still get crash with solution above. I need to use local variable in the function Aws::String GetHttpClientMetricNameByType. and after pass previous crashing, we get another crash

[CortexSync_2019-03-27-164258_Cuongs-MacBook-Pro-2.crash.zip](https://github.com/aws/aws-sdk-cpp/files/3012523/CortexSync_2019-03-27-164258_Cuongs-MacBook-Pro-2.crash.zip)
assertion failed: (s_monitors), function OnRequestSucceeded
@singku do you have any idea ?

**Comment by nguoithichkhampha** [comment] 2019-03-27 09:59
another crash , now from Assertion failed: (s_HttpClientFactory), function CreateHttpRequest
[CortexSync_2019-03-27-165656_Cuongs-MacBook-Pro-2.crash.zip](https://github.com/aws/aws-sdk-cpp/files/3012562/CortexSync_2019-03-27-165656_Cuongs-MacBook-Pro-2.crash.zip)

**Comment by nguoithichkhampha** [comment] 2019-03-27 11:15
Ah, I found the root cause. You have a static unique pointer in MonitoringManager.cpp. and this pointer is used in multithreading.
when call function Init . this pointer is created in thread 0x10cedf5c0
but in function callback OnRequestSucceeded or OnRequestFailed
you check this pointer on another thread "Monitors check  on thread 0x7000094a0000"
I think amazon already support multithread request ?
and this is a bug on your side ?

**Comment by nguoithichkhampha** [comment] 2019-03-27 12:17
After look at in the document. I don't see anyway to stop thread download before call ShutdownAPI().
except call `requestPtr->WaitUntilFinished();` for each request
Do you have any idea ?

**Comment by singku** [comment] 2019-03-27 14:39
In the logical level, you have to make sure all threads finished their job before calling ShutdownAPI. For this case, you can call requestptr->Cancel() to stop threads from further downloading. Then to call requestptr->WaitUntilFinished() to make sure threads are done. Then to call ShutdownAPI

**Comment by nguoithichkhampha** [comment] 2019-03-27 16:28
okay, look like previous crash and new crash have same the cause. I tried to log size of map before call function metricsTypeToName.find(static_cast(type)); and it always output size = 9. that mean crash happens in destroy time, not in initial time.
I think should not use static variable in multithreading. it's not thread safe and have many problems behind.

**Comment by singku** [comment] 2019-03-27 17:15
Global (static) variables are initialized before program starts. Local static variables are initialized when program first hits the declaration and concurrent call should wait until initialization finished. In either case, it's thread safe. 

Since you have found the root cause, and it's caused by lingering thread accessing aws related memory after shutdownAPI. I am going to close this issue.

**Closed by singku** 2019-03-27 17:15 UTC
Labels: help wanted
