### ISSUE TITLE
s3 client cannot recover from clock drift

### ISSUE THREAD

**Issue by hrjaco** [aws/aws-sdk-cpp#700] opened 2017-10-19 22:57 UTC
### What platform/OS are you using?
Ubuntu 12

### What compiler are you using? what version?
gcc 5.4.1

### Can you provide a TRACE level log? (sanitize any sensitive information)
This is the error message we see. "The difference between the request time and the current time is too large." We will keep getting this once the clock drift happens, and even if the clock drift has been fixed by ntp.

**Comment by marcomagdy** [comment] 2017-10-20 15:21
What version of the SDK are you using?

**Comment by hrjaco** [comment] 2017-10-20 16:05
i am using https://github.com/aws/aws-sdk-cpp/commit/39a03136ef8525bc94d82669432491e653154677.

**Comment by marcomagdy** [comment] 2017-10-20 21:09
This is a duplicate of https://github.com/aws/aws-sdk-cpp/issues/577
The issue has been fixed. You should upgrade to at least v1.1.3

**Closed** 2017-10-20 21:09 UTC

**Comment by hrjaco** [comment] 2017-11-06 18:27
We recently upgraded our version to 1.2.7. But we are still seeing this issue "The difference between the request time and the current time is too large.". It cannot recover by itself. We have to restart the process in order to recover...

Any idea what's going on?

**Comment by marcomagdy** [comment] 2017-11-06 18:45
We need TRACE logs to be able to help you with that. (remember to remove any sensitive information before posting the logs here)

**Comment by hrjaco** [comment] 2017-11-06 18:48
What's the TRACE logs you are talking about?
