### ISSUE TITLE
On building static library of S3 or S3-CRT on windows doesn't set all dependent libraries Runtime Library property to "/MT(Release)", "/MTd(Debug)"

### ISSUE THREAD

**Issue by BaffledCoder** [aws/aws-sdk-cpp#2099] opened 2022-09-20 10:32 UTC
### Describe the bug

While building S3 or S3-CRT as a static library (BUILD_SHARED_LIBS=OFF) all dependencies other than cpp-sdk-core, and crt-cpp are set to Multi-threaded DLL (/MD).
I have even tried disabling FORCE_SHARED_CRT.
Here is the CMake command used by me  for building S3-CRT:
cmake ..\ -G "Visual Studio 15 Win64" -DBUILD_ONLY="s3-crt" -DBUILD_SHARED_LIBS=OFF -DCPP_STANDARD=17 -DTARGET_ARCH=WINDOWS  -DENABLE_TESTING=OFF -DFORCE_SHARED_CRT=OFF 

### Expected Behavior

When Build as a static library all dependencies along with the main project should have runtime library property set to "/MT(Release)", "/MTd(Debug)"

### Current Behavior

Other than aws-cpp-sdk-s3-crt, aws-cpp-sdk-core, and aws-crt-cpp all other dependencies are built with the runtime library \MD configuration.

### Reproduction Steps

Run the following CMake command:
cmake ..\ -G "Visual Studio 15 Win64" -DBUILD_ONLY="s3-crt" -DBUILD_SHARED_LIBS=OFF -DCPP_STANDARD=17 -DTARGET_ARCH=WINDOWS  -DENABLE_TESTING=OFF -DFORCE_SHARED_CRT=OFF 

### Possible Solution

Every library should inherit STATIC_CRT as it is set in top level CMake when BUILD_SHARED_LIBS is set to OFF

### AWS CPP SDK version used

1.9

### Compiler and Version used

Visual Studio

### Operating System and version

Windows 11

**Comment by jmklix** [comment] 2022-09-20 23:56
This looks like it's a duplicate of this [issue](https://github.com/aws/aws-sdk-cpp/issues/2056). Still working on a fix. Closing this issue, please look to the linked issue for updates about this.

**Closed by jmklix** 2022-09-20 23:56 UTC
Labels: bug, needs-triage
