### ISSUE TITLE
transcribestream still doesn't work

### ISSUE THREAD

**Issue by ambitslix** [aws/aws-sdk-cpp#2287] opened 2023-01-12 06:57 UTC
### Describe the bug

aws-doc-sdk-examples fails with

./get_transcript 
Starting...
ERROR: A complete signal was sent without the preceding empty frame.
Failed to create a stream
Failed to send an empty frame

### Expected Behavior

Test should pass

### Current Behavior

Exception:
ERROR: A complete signal was sent without the preceding empty frame.

### Reproduction Steps

Run the 

aws-doc-sdk-examples get_transcript test

### AWS CPP SDK version used

1.10.48

### Compiler and Version used

11.3.0

### Operating System and version

Ubuntu

**Comment by jmklix** [comment] 2023-01-12 19:01
Are you following [this](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/cpp/example_code/transcribe) example?

**Comment by ambitslix** [comment] 2023-01-12 19:11
Yes, definitely.

**Comment by ambitslix** [comment] 2023-01-12 19:11
> Are you following [this](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/cpp/example_code/transcribe) example?

Yes, definitely.

**Comment by jmklix** [comment] 2023-01-12 19:32
Which version of Ubuntu are you using?
Can you [enable logging](https://github.com/aws/aws-sdk-cpp/blob/main/Docs/SDK_usage_guide.md#logging) and include them as well.

**Comment by ambitslix** [comment] 2023-01-12 22:00
Sure,

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

[aws_sdk_2023-01-12-06.log](https://github.com/aws/aws-sdk-cpp/files/10406386/aws_sdk_2023-01-12-06.log)

**Comment by jmklix** [comment] 2023-02-14 23:11
I'm able to successfully run the sample with ubuntu 22.04.1 on an amazon ec2 instance. I see that the error you are getting is preceded by a `BadRequestException'. Have you set up your credentials correctly with the right permissions to use this service?

**Comment by ambitslix** [comment] 2023-02-17 05:43
Hello,

I just re-checked my permissions in IAM. I have full access to AWSPolly and AWSTranscribe. Furthermore I have been testing AWSPolly without any issues. The same credentials should work for AWSTranscribe so I assume the issue must be elsewhere and not with credentials. I have also tested the online AWS transcription via the browser and it worked although I think the browser uses separate logon.

**Comment by ambitslix** [comment] 2023-02-24 20:24
> I'm able to successfully run the sample with ubuntu 22.04.1 on an amazon ec2 instance. I see that the error you are getting is preceded by a `BadRequestException'. Have you set up your credentials correctly with the right permissions to use this service?

Still getting this after checking all permissions are good. Just giving you a heads up.

**Comment by jmklix** [comment] 2023-03-09 18:34
Hey when looking through your logs the first error I see is
```
[ERROR] 2023-01-12 06:02:31.074 CurlHttpClient [140663358203456] Curl returned error code 55 - Failed sending data to the peer
```
This is fairly a runtime dependent error and comes because around because of dependencies, Are you running this from your laptop? are you running this from a EC2 instance? can you replicate your environment where this occurs in a docker image?
The other issues I see is
```
[ERROR] 2023-01-12 06:02:40.085 CurlHttpClient [140663358203456] Curl returned error code 28 - Timeout was reached
```
We set the curl option
```
curl_easy_setopt(handle, CURLOPT_LOW_SPEED_LIMIT, m_lowSpeedLimit)
```
Which is described by curl as
>Pass a long as parameter. It contains the average transfer speed in bytes per second that the transfer should be below during [CURLOPT_LOW_SPEED_TIME](https://curl.se/libcurl/c/CURLOPT_LOW_SPEED_TIME.html) seconds for libcurl to consider it to be too slow and abort.
by default in the SDK this is 1, and will terminate your connection if you drop below 1 byte per second, if your runtime is constrained and you will allow for it to drop to lower than 1 byte per second you can disable this  with
```
ClientConfiguration clientConfiguration;
clientConfiguration.lowSpeedLimit = 0;
```
Which will never terminate the connection. I would suggest trying this out.

**Comment by ambitslix** [comment] 2023-03-10 22:00
This is running on a powerful desktop, my connection is 1Gb up and down. I tried the lowSpeedLimit and re-compiled but the exact same error occurs. Again AWS-polly works fine. I checked and get_transcript is linked with local version of curl which is very recent.  The first error is actually what is below in the [DEBUG] section.

```

[TRACE] 2023-03-10 21:47:49.766 ConcurrentStreamBuf [140078001153600] Stream characters in buffer: 1024
[DEBUG] 2023-03-10 21:47:49.766 CURL [140078001153600] (Text) [CONN-0-0][CF-TCP] recv(len=5) -> -1, err=81

[DEBUG] 2023-03-10 21:47:49.766 CURL [140078001153600] (SSLDataOut) 5bytes
[DEBUG] 2023-03-10 21:47:49.766 CURL [140078001153600] (Text) [CONN-0-0][CF-TCP] send(len=1053) -> 1053, err=0

[DEBUG] 2023-03-10 21:47:49.766 CURL [140078001153600] (DataOut) 
```
Then the first [ERROR] section appears later:

```
[TRACE] 2023-03-10 21:47:57.585 ConcurrentStreamBuf [140078001153600] Stream characters in buffer: 1024
[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (SSLDataOut) 5bytes
[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (Text) Send failure: Broken pipe

[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (Text) [CONN-0-0][CF-TCP] send(len=1053) -> -1, err=55

[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (Text) OpenSSL SSL_write: Broken pipe, errno 32

[TRACE] 2023-03-10 21:47:57.586 ConcurrentStreamBuf [140078001153600] Stream characters in buffer: 1024
[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (Text) Closing connection 0

[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (Text) [CONN-0-0][CF-TCP] recv(len=5) -> 5, err=0

[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (SSLDataIn) 5bytes
[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (Text) [CONN-0-0][CF-TCP] recv(len=161) -> 161, err=0

[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (Text) [CONN-0-0][CF-TCP] cf_socket_close(20) active

[DEBUG] 2023-03-10 21:47:57.586 CURL [140078001153600] (Text) socket_close(20)

[ERROR] 2023-03-10 21:47:57.586 CurlHttpClient [140078001153600] Curl returned error code 55 - Failed sending data to the peer
[DEBUG] 2023-03-10 21:47:57.587 CurlHandleContainer [140078001153600] Destroy curl handle: 0x7f6658008d50
[DEBUG] 2023-03-10 21:47:57.587 CurlHandleContainer [140078001153600] Created replacement handle and released to pool: 0x7f665805ef70
[DEBUG] 2023-03-10 21:47:57.587 AWSClient [140078001153600] Request returned error. Attempting to generate appropriate error codes from response
[ERROR] 2023-03-10 21:47:57.587 AWSJsonClient [140078001153600] HTTP response code: -1
Resolved remote host IP address: 54.212.20.242
Request ID: 
Exception name: 
Error message: curlCode: 55, Failed sending data to the peer
14 response headers:
content-type : application/vnd.amazon.eventstream
date : Fri, 10 Mar 2023 21:47:49 GMT
transfer-encoding : chunked
x-amzn-request-id : dc20554c-7d63-46f8-9a9a-248179fdade2
x-amzn-requestid : dc20554c-7d63-46f8-9a9a-248179fdade2
x-amzn-transcribe-enable-channel-identification : false
x-amzn-transcribe-enable-partial-results-stabilization : false
x-amzn-transcribe-identify-language : false
x-amzn-transcribe-identify-multiple-languages : false
x-amzn-transcribe-language-code : en-US
x-amzn-transcribe-media-encoding : pcm
x-amzn-transcribe-sample-rate : 8000
x-amzn-transcribe-session-id : 20fdc5a1-a621-4ae3-a7da-05e2ee123cc6
x-amzn-transcribe-show-speaker-label : false
[WARN] 2023-03-10 21:47:57.587 AWSClient [140078001153600] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
[DEBUG] 2023-03-10 21:47:57.587 AWSClient [140078001153600] Server time is Fri, 10 Mar 2023 21:47:49 GMT, while client time is Fri, 10 Mar 2023 21:47:57 GMT
[WARN] 2023-03-10 21:47:57.587 AWSClient [140078001153600] Request failed, now waiting 0 ms before attempting again.
[DEBUG] 2023-03-10 21:47:57.588 AWSAuthEventStreamV4Signer [140078001153600] Canonical Header String: amz-sdk-invocation-id:C10385C0-326F-4318-9BF2-D6255B5E0A3E
amz-sdk-request:ttl=20230310T214752Z; attempt=2; max=11
content-type:application/vnd.amazon.eventstream
host:transcribestreaming.us-west-2.amazonaws.com
x-amz-api-version:2017-10-26
x-amz-content-sha256:STREAMING-AWS4-HMAC-SHA256-EVENTS
x-amz-date:20230310T214757Z
x-amzn-transcribe-language-code:en-US
x-amzn-transcribe-media-encoding:pcm
x-amzn-transcribe-sample-rate:8000
```

**Comment by jmklix** [comment] 2023-03-15 20:38
Are you behind a corporate firewall or have some special network settings that might be blocking some of the requests?

**Comment by ambitslix** [comment] 2023-03-15 20:57
> Are you behind a corporate firewall or have some special network settings that might be blocking some of the requests?

I'm not, just personal firewall but even if I was I'm not aware of any special port requirements to use this AWS service? AWSPolly works. Or should I run the python version of this test to rule this out?

**Comment by jmklix** [comment] 2023-03-15 23:52
Trying to repro it with python would be a good idea. I'm still unsure what might be causing this and if it does(or doesn't) happen with another sdk that would be helpful to know

**Comment by ambitslix** [comment] 2023-03-16 17:06
Okay I've tested the following python transcription example:

https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/python/example_code/transcribe
```
$python transcribe_basics.py
```
It works without any issues. Are you sure that you've tested the

aws-doc-sdk-examples/cpp/example_code/transcribe/get_transcript

and it worked for you?

**Comment by sbiscigl** [comment] 2023-03-16 17:38
Yes we have tested and verified it with several platforms, one of them being AL2, specific docker file:

```
# Using offical Amazon Linux 2 image from public ECR
FROM public.ecr.aws/amazonlinux/amazonlinux:2

#Install java
RUN amazon-linux-extras enable corretto8 && yum install -y java-1.8.0-amazon-corretto

#Install g++
RUN yum groupinstall "Development Tools" -y

#Install required dependencies
RUN yum install -y curl-devel openssl-devel ninja-build maven cmake3 awscli jq clang gcc10 gcc10-c++ bison rsync

#Link cmake3 correctly
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

#Build from source
RUN git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp && \
    cd aws-sdk-cpp && \
    mkdir build && \
    cd build && \
    cmake .. -G "Unix Makefiles" -DBUILD_ONLY="transcribestreaming;transcribe" && \
    make install

```

I see that you are using mint/ubuntu earlier. Are you able to replicate your dependencies in a dockerfile? that way we could replicate it as well?

**Comment by ambitslix** [comment] 2023-03-16 17:45
Well I could replicate my dependencies in a docker but let me check and run your docker test to see if that works? Would I be able to run yours in my workstation?

**Comment by sbiscigl** [comment] 2023-03-16 18:06
yeah, everything there you can/should be able to use, that would really be appreciated if you could give that a shot! give me a shout if that works or not. if it does work we can start narrowing down why your deps dont work.

**Comment by sbiscigl** [comment] 2023-03-16 18:46
apologies, i spent a little more time on it and i can provide a more complete set of docker file and instructions now, the latter lacked how to run it. so give the dockerfile

```
# Using offical Amazon Linux 2 image from public ECR
FROM public.ecr.aws/amazonlinux/amazonlinux:2

#Install java
RUN amazon-linux-extras enable corretto8 && yum install -y java-1.8.0-amazon-corretto

#Install g++
RUN yum groupinstall "Development Tools" -y

#Install required dependencies
RUN yum install -y curl-devel openssl-devel ninja-build maven cmake3 awscli jq clang gcc10 gcc10-c++ bison rsync

#Link cmake3 correctly
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

#Build sdk from source
RUN git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp && \
    cd aws-sdk-cpp && \
    mkdir build && \
    cd build && \
    cmake .. -G "Unix Makefiles" -DBUILD_ONLY="transcribestreaming;transcribe" && \
    make install

#Build transcribe samples
RUN git clone https://github.com/awsdocs/aws-doc-sdk-examples.git && \
    cd aws-doc-sdk-examples/cpp/example_code/transcribe && \
    mkdir build && \
    cd build && \
    cmake .. -G "Unix Makefiles" && \
    make
```

once you have that file from the dir you can run
```
docker build -t transcribe-issue .
```

followed by
```
docker run \
-e AWS_ACCESS_KEY_ID=your-access-key \
-e AWS_SECRET_ACCESS_KEY=your-secret-key \
-e AWS_SESSION_TOKEN=your-session-token \
--name transcribe-issue \
-it transcribe-issue /aws-doc-sdk-examples/cpp/example_code/transcribe/build/get_transcript
```

to actually run the example. let me know how that works for you.

**Comment by ambitslix** [comment] 2023-03-16 20:11
That worked:
```
Starting...
[partial] But what
[partial] But what if somebody
[partial] But what if somebody decides?
[partial] But what if somebody decides to break it?
[partial] But what if somebody decides to break it? Be careful.
[partial] But what if somebody decides to break it? Be careful that you can
[partial] But what if somebody decides to break it? Be careful that you keep
[partial] But what if somebody decides to break it? Be careful that you keep adequate.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage, But look for places.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage, but look for places to save.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage but look for places to save money.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking long.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get thing.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things square.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away. Then the bankers
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away. Then the bankers expect
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away. Then the bankers expected
File: only 880 could be read
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away. Then the bankers expected hiring the wife.
Successfully sent the empty frame
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away. Then the bankers expected during the why, for once.
[partial] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away. Then the bankers expected during the Y for one's company.
[Final] But what if somebody decides to break it? Be careful that you keep adequate coverage. But look for places to save money. Maybe it's taking longer to get things squared away. Then the bankers expected during the Y for one's company.
Done
```
I've looked and the containers version of curl is:

```
RUN yum info libcurl
 ---> Running in 0efd28e75b60
Loaded plugins: ovl, priorities
Installed Packages
Name        : libcurl
Arch        : x86_64
Version     : 7.88.1
...
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k

```

While the version I'm linking is master from github v8.0.0-dev. I'm also linking with openssl 3.1 latest .

**Comment by ambitslix** [comment] 2023-03-17 07:53
...Update, built openssl 1.0.2k for linking and the same issue manifests.

**Comment by sbiscigl** [comment] 2023-03-17 14:30
I can run it on ubuntu with the following docker image (same instructions as above).

```
FROM public.ecr.aws/lts/ubuntu:22.04_stable

RUN apt-get update && \
  apt-get install build-essential cmake git libcurl4-openssl-dev zlib1g-dev libssl-dev -y

#Build sdk from source
RUN git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp && \
    cd aws-sdk-cpp && \
    mkdir build && \
    cd build && \
    cmake .. -G "Unix Makefiles" -DBUILD_ONLY="transcribestreaming;transcribe" && \
    make install

#Build transcribe samples
RUN git clone https://github.com/awsdocs/aws-doc-sdk-examples.git && \
    cd aws-doc-sdk-examples/cpp/example_code/transcribe && \
    mkdir build && \
    cd build && \
    cmake .. -G "Unix Makefiles" && \
    make
```

i know that that is not the version of curl and open ssl you are referring to, but with this setup it it will work on ubuntu. If you could update this docker file to reflect your deps to reproduce it, it will be a lot easier for us to debug it as we will have a baseline of exactly what deps are wrong.

**Comment by ambitslix** [comment] 2023-03-17 15:41
Ok I will try to build a docker image with the issue manifested. BTW I tried to build with the stock system openssl and curl and it also has the issue. So for now the versions of openssl and curl I've used originally to locally link has the issue, the systemwide(apt) libs has the issue and even if I link the same versions as in your AL2 docker libs also has the issue. So it seems that it works in the AL2 docker container but not when linked on my machine. This seems to suggest the issue is not with these two libraries. So it's either another dependency or it's a gcc bug in my version. But now if it works in your Ubuntu 22 docker I'm really lost as to what it could be...? I will try to build over the Ubuntu 22 docker.

**Comment by ambitslix** [comment] 2023-03-17 17:01
...Ok it works after all when linked with the stock system libraries. What must have happened was that it was still picking up something from the locally built curl/openssl. So I think the issue is when I locally build curl/openssl something isn't quite right with the resulting libraries or linking sequence to aws-sdk. Actually I often see the following:

```
[ 95%] Linking CXX executable transcribestreaming-gen-tests
./transcribestreaming-gen-tests: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
Even though libssl.so is there in the local directory and CMAKE_PREFIX_PATH points to that lib dir.

**Comment by sbiscigl** [comment] 2023-03-17 20:05
```
ERROR: A complete signal was sent without the preceding empty frame.
Failed to create a stream
Failed to send an empty frame
ERROR: A complete signal was sent without the preceding empty frame.
```

thank you so much for providing this, happy to say i can replicate. we can start a investigation into why these deps and these versions cause this.

**Comment by ambitslix** [comment] 2023-03-17 20:14
Sure, my guess is that the versions of those deps should not matter much it's some kind of linkage problem.

**Comment by ambitslix** [comment] 2023-03-20 05:49
...Update, I debugged my application with the workaround and I was perplexed to find that it still had this bug. Then I ran the get_transcript test from within my application and it worked. As I re-checked my logic I saw that I had prematurely called Aws::TranscribeStreamingService::Model::AudioStream::Close(), after with the my code was still writing to it. This has the same symptom as the bug. I fixed my code and now my application works. However I'm wondering if the bug isn't some kind of race condition which closes the stream prematurely. This can happen if the semaphores aren't initialized for example.

**Comment by jmklix** [comment] 2023-03-23 21:25
Did you need any more help with transcribe streaming while using this sdk?

**Comment by ambitslix** [comment] 2023-03-23 21:57
Not at the moment, however I would  not consider this resolved. I'm simply using a workaround to make it work for now. The issue still exists as I demonstrated with the docker setup when the SDK is built locally from sources.

**Comment by gjasny** [comment] 2023-07-11 06:24
The issue goes away if you build your local curl with http2 support (by adding nghttp2).

**Comment by jmklix** [comment] 2023-11-28 17:58
Closing this issue as it seems to be working correctly now if you use the correct version of [curl/openssl](https://github.com/aws/aws-sdk-cpp/issues/2287#issuecomment-1474256931):
> The workaround for now is to link with systemwide curl/openssl.

Please let us know if you are still running into any problems with transcribestream.

**Closed by jmklix** 2023-11-28 17:58 UTC
Labels: bug, p2
