### ISSUE TITLE
LNK2001 unresolved external error when building solution when calling InitAPI

### ISSUE THREAD

**Issue by LazzariPaolo** [aws/aws-sdk-cpp#1154] opened 2019-06-04 13:30 UTC
### What platform/OS are you using?
Windows 10

### Which version of the SDK?
1.7.114

### What compiler are you using? what version?
Visual Studio 2015

### What are your CMake arguments?
cmake 'C:\Program Files\aws\aws-sdk-cpp' -G "Visual Studio 14 Win64" -DCMAKE_BUILD_TY
PE=Release

I then install the SDK with:

msbuild .\INSTALL.vcxproj /p:Configuration=Release

### Can you provide a TRACE level log? (sanitize any sensitive information)

The build occurs successfully and the .lib files are created.

In VS, I express dependencies to the .libs 

- C/C++ -> General-> Additional Include Directories:

C:\Program Files\aws-cpp-sdk-all\include

- Linker -> General -> Additional Library Directories

C:\Program Files\aws-cpp-sdk-all\bin

I can build the solution fine for the following code:

```
#include <aws/batch/BatchClient.h>
#include <aws/batch/model/ContainerOverrides.h>
#include <aws/batch/model/KeyValuePair.h>
#include <aws/batch/model/SubmitJobRequest.h>
#include <aws/core/Aws.h>
#include <aws/core/utils/Outcome.h>

int main(void)
{
	Aws::SDKOptions options;
}
```

But as soon as I make a call to InitAPI:

```
#include <aws/batch/BatchClient.h>
#include <aws/batch/model/ContainerOverrides.h>
#include <aws/batch/model/KeyValuePair.h>
#include <aws/batch/model/SubmitJobRequest.h>
#include <aws/core/Aws.h>
#include <aws/core/utils/Outcome.h>

int main(void)
{
	Aws::SDKOptions options;
	Aws::InitAPI(options);
}
```
I get the following error:

**Error	LNK2001	unresolved external symbol "void __cdecl Aws::InitAPI(struct Aws::SDKOptions const &)" (?InitAPI@Aws@@YAXABUSDKOptions@1@@Z)	AWSBatch	C:\Users\paolol\source\repos\AWSBatch\AWSBatch\Source.obj**	

I have tried on Visual Studio 2015, Visual Studio 2017, Visual Studio 2019 in release mode.

**Comment by KaibaLopez** [comment] 2019-06-05 23:36
Hi and thanks for reaching out @LazzariPaolo,
It looks like you're not linking the library properly to your project, the SDKOptions is a struct defined directly in the Aws.h file, so the include is enough for that, but for the InitAPI function you must link the library files. 
In your case, you'd have open the project properties and add: 
Linker -> Input -> Additional Dependencies:
  aws-cpp-sdk-core.lib
Linker -> General -> Additional Library Directories
  Location to .lib file ( something like [your build directory]\aws-cpp-sdk-core\Release )

Could you try that and see if it works for you?

**Comment by LazzariPaolo** [comment] 2019-06-07 08:25
Thank you very much @KaibaLopez ! It works great. 

For future readers, my successful configuration is the following:

- C/C++ - > General -> Additional Include Directories: **C:\Program Files\aws-cpp-sdk-all\include;**
- Linker - > General -> Additional Library Directories: **C:\Program Files\aws-cpp-sdk-all\bin;**
- Linker - > Input - > Additional Dependencies: **aws-cpp-sdk-core.lib;**

**Comment by LazzariPaolo** [comment] 2019-06-07 10:01
Hey @KaibaLopez , I have added the **aws-cpp-sdk-batch.lib** to the linker input but I get an issue when building the following code:

```
#include <aws/batch/BatchClient.h>
#include <aws/batch/model/ContainerOverrides.h>
#include <aws/batch/model/KeyValuePair.h>
#include <aws/batch/model/SubmitJobRequest.h>
#include <aws/core/Aws.h>
#include <aws/core/utils/Outcome.h>
#include <aws/core/utils/json/JsonSerializer.h>

int main(void)
{
	Aws::SDKOptions options;
	Aws::InitAPI(options);

	Aws::Batch::BatchClient batchClient;
	Aws::Batch::Model::SubmitJobRequest submitJobRequest;

	Aws::ShutdownAPI(options);
}
```
Error	LNK2001	unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3PEBDEB)	Project1	C:\Users\paolol\Desktop\Project1\Project1\Source.obj	1	

Error	LNK2001	unresolved external symbol "char const * const Aws::Http::API_VERSION_HEADER" (?API_VERSION_HEADER@Http@Aws@@3PEBDEB)	Project1	C:\Users\paolol\Desktop\Project1\Project1\Source.obj	1	

Error	LNK1120	2 unresolved externals	Project1	C:\Users\paolol\Desktop\Project1\x64\Release\Project1.exe	1	

Do you have any suggestions? Thanks!

**Comment by KaibaLopez** [comment] 2019-06-07 22:26
Hi @LazzariPaolo, yea I'm getting these same errors, and after doing some digging, according to [this error description](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?view=vs-2019) this is caused because the sdk has inline definitions in some of the cpp files. 
Feel free to investigate further, but if I'm getting it right, that would mean we can't link the libraries this way. 

Now, as a sort of workaround for using the sdk with visual studio, I've gotten it to work by building my project together with the sdk, using its CMake plugin and having my project in the same folder as the sdk source:
 
To do so, I mostly followed this tutorial: _[CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019)_ , to use the cmake plug in, I modified the cmakelists.txt file in the main source folder and added my project to it. 

I'll keep looking for better ways to go around this and please comment further if you find a better workaround, but since this is more of a Visual Studio usage problem than the sdk's I'll be closing it soon.

**Comment by KaibaLopez** [comment] 2019-06-10 23:58
Hi @LazzariPaolo
I took another look at it and I was wrong on my last comment. 

The problem is that we had missing preprocessor definitions, so some of the macros (in our case AWS_CORE_API) end up defined as empty and thus, gives a linking error when trying to use them for variable definitions.

To get it to work on your build, you have to add these preprocessor definitions in the project properties:

* C/C++ - > Prreprocessor -> Preprocessor Definitions: WIN32;_WINDOWS;PLATFORM_WINDOWS;ENABLE_BCRYPT_ENCRYPTION;ENABLE_WINDOWS_CLIENT;AWS_SDK_VERSION_MAJOR=1;AWS_SDK_VERSION_MINOR=7;AWS_SDK_VERSION_PATCH=116;USE_WINDOWS_DLL_SEMANTICS;USE_IMPORT_EXPORT=1;AWS_EVENT_STREAM_USE_IMPORT_EXPORT;AWS_COMMON_USE_IMPORT_EXPORT;CMAKE_INTDIR="Release";%(PreprocessorDefinitions)

This should get the build to complete correctly, but in order to run it and debug it make sure to also add the dlls to the Release (or Debug) folder.

**Comment by singku** [comment] 2019-06-11 18:33
If I remember it well, define `USE_WINDOWS_DLL_SEMANTICS` and `USE_IMPORT_EXPORT` should be enough.

As always, I suggest you to follow this doc to generate your own MSVC solution, which is much easier. https://aws.amazon.com/blogs/developer/developer-experience-of-the-aws-sdk-for-c-now-simplified-by-cmake/

**Closed** 2019-06-11 21:25 UTC
Labels: guidance

**Comment by syedzia5** [comment] 2019-11-12 13:16
I also was facing the same problem. using the solution mentioned here the link errors vanished but now I am getting aws-cpp-sdk-core.dll is missing on your computer. kindly help.

**Comment by KaibaLopez** [comment] 2019-11-12 18:33
Hi @syedzia5, 
> this will build the project but in order to run it you’ll still need to add the sdk’s dlls (commons,checksum,core,etc) to the executable directory.

Did you do this part? 
For reference, the dll files should be created when the sdk is built at: "<build_directory>\bin\Release" or "<build_directory>\bin\Debug" depending on the build type.
Then you'd want to take that dll file and put it in the same folder as your app's executable so something like:
"<your_App>\x64\Debug"
