### ISSUE TITLE
sdk crashing in various string operations on windows

### ISSUE THREAD

**Issue by nomercy78** [aws/aws-sdk-cpp#613] opened 2017-07-15 21:53 UTC
I am trying to use sdk in a qt5 project on windows platform.
using latest sdk with latest qt5 versions.
I tried with and without mem managemet, result differs a bit but almost always fail with some string operation access violation error.
btw using aws sdk in a QThread could this be an issue?
what could be wrong, what can I do?
Thank you.

**Comment by singku** [comment] 2017-07-20 17:41
Do you have detailed description of the crash? Such as code snippet, your use case, as well as core dump msg.

**Comment by nomercy78** [comment] 2017-07-20 17:50
Actually I think, I have figured out. it is Qt5 (didn't test with 4 and my setup was msvc 2015 version).
Even if it is a simple for aws only console app, it crashes on some form of string operation, usually in msvc libs (like xstring, wcslen, etc..).

**Comment by singku** [comment] 2017-07-20 18:04
Hmm, so you figured out the reason or figured out the way to solve?

**Comment by nomercy78** [comment] 2017-07-20 19:10
I figured out the reason (Qt) and it was a real bummer to not being able to use sdk inside a Qt app but as soon as I figured I moved that part out to an indpendant exe so yes it was solved on my part but not on aws part...
I think it should be a bug report that needs to be solved.

**Comment by singku** [comment] 2017-07-20 19:15
Could you please elaborate the details? We have a internal branch building our SDK against Qt, it works fine though.

**Comment by nomercy78** [comment] 2017-07-20 19:30
I was trying to use sdk inside a Qt5 msvc2015 (written and compiled on Qt Crerator - qmake) app for some s3 uploads and trying to use it with SimpleAWSCredentials and first it happened on SimpleAWSCredentials constructer (inside copy constructer's get methods) the I tried to use it without constructer and used set methods, tried with and without custom memory management, tried on different systems, tried to pass credentials as provider with little more success but in the end they all failed on some sort of string function inside msvc dll's. (and it was always access violation error)
I don't know what else to say but I hope it helps...

**Comment by jt70471** [comment] 2017-07-20 23:05
I am also successfully using the AWS CPP SDK with Qt5, but it's on a Mac, not Windows. Curious if you see the access violations when not using threads or not.

**Comment by nomercy78** [comment] 2017-07-21 06:32
I was also suspicious about that at first and tried the sample code in this git with plain main.cpp only with similiar results...

**Comment by TyrasNistru** [comment] 2017-08-15 00:32
Is there any development on this? I can confirm this bug.

**Comment by AMagill** [comment] 2017-11-22 00:05
I just spent a couple hours banging my head against a problem very much like this.  **It turned out the issue was that I had mixed up the debug and release versions of the AWS SDK DLLs.**  A debug build of my program trying to use release built AWS DLLs would consistently fail on string operations.  I guess (at least in my case of VS2017 on Windows) there must be some runtime incompatibility between the debug and release versions of std::string, and my application was using one and the AWS DLL was using the other.

**Comment by nomercy78** [comment] 2017-11-22 09:51
no it was not the case with me, I tried relase version too, it was crashing. though I haven’t tried again since.

Best Regards,
Emre Besirik

**Comment by singku** [comment] 2019-04-16 16:32
@nomercy78 Do you still encounter crashes?

**Comment by nomercy78** [comment] 2019-04-16 19:17
Hi,
I actually haven't tried it since then. I can though if you need me to?
Best Regards

**Comment by singku** [comment] 2019-05-07 06:30
Yes, please update SDK to latest version and try that again. Thank you. I am looking forward to hearing what would happen.

**Comment by woohoou** [comment] 2019-10-31 11:00
I had errors in xstring but it was fixed with release compilation.

**Closed** 2019-10-31 21:43 UTC
Labels: guidance, response-requested
