### ISSUE TITLE
S3 PutObject official example results in zero byte uploaded file

### ISSUE THREAD

**Issue by imdario** [aws/aws-sdk-cpp#417] opened 2017-01-18 16:45 UTC
We are integrating the SDK in order to get and put files in S3. We found that [the official example](https://github.com/awsdocs/aws-doc-sdk-examples/blob/74ceba526ec68be8014923e8695575a3d7041826/cpp/example_code/s3/put_object.cpp) uploads the file as empty.

We found a workaround using std classes and setting the content length. If we try doing the same with SDK's Fstream and setting the content length, it doesn't work either.

What can be wrong with FStream in the official example?

Please find below our working code:

```cpp
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/PutObjectRequest.h>
#include <iostream>
#include <fstream>

int main(int argc, char** argv)
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);

    if(argc < 3) {
        std::cout << std::endl <<
            "To run this example, supply the name of an S3 bucket and object to"
            << std::endl << "upload to it." << std::endl << std::endl <<
            "Ex: put_object <bucketname> <filename>\n" << std::endl;
        exit(1);
    }

    const Aws::String bucket_name = argv[1];
    const Aws::String key_name = argv[2];
    const Aws::String dir_name = ".";

    std::cout << "Uploading " << key_name << " to S3 bucket: " <<
        bucket_name << std::endl;

    Aws::S3::S3Client s3_client;

    Aws::S3::Model::PutObjectRequest object_request;
    object_request.WithBucket(bucket_name).WithKey(key_name);

    // Here goes what we did differently
    auto input_data = std::make_shared<std::fstream>(key_name.c_str(), std::ios_base::in);
    input_data->seekp(0, std::ios_base::end);

    object_request.SetBody(input_data);
    object_request.SetContentLength(static_cast<long>(object_request.GetBody()->tellp()));
    // Here ends what we did differently

    auto put_object_outcome = s3_client.PutObject(object_request);

    if(put_object_outcome.IsSuccess()) {
        std::cout << "Done!" << std::endl;
    }
    else {
         std::cout << "PutObject error: " <<
             put_object_outcome.GetError().GetExceptionName() << " " <<
             put_object_outcome.GetError().GetMessage() << std::endl;
    }

    Aws::ShutdownAPI(options);
}
```

We are using the SDK at commit 4a15890a62d6f94f5ca356f8e84ea8597184cd72, compiled using GCC 4.9 under kernel 3.10.0-327.36.3.el7.i686 (CentOS Linux release 7.2.1511 (AltArch)).

**Comment by bretambrose** [comment] 2017-01-18 17:48
Do the properties you construct the stream with match the properties of the file? (std::ios::binary for example)

**Comment by imdario** [comment] 2017-01-19 07:23
Yes, they do. The properties match and they work with std::fstream but not with AWS::FStream.

**Comment by bretambrose** [comment] 2017-01-19 14:54
std::fstream and Aws::FStream are essentially the same thing; the allocator makes no functional difference.  Are you saying that you can take your code example above and just change std::fstream to Aws::FStream and it stops working, with no other changes?

Can you step through your non-working example and find out why?

What are your cmake arguments for building the SDK?

**Comment by imdario** [comment] 2017-01-19 15:37
Indeed. It stops working as soon as we replace std::make_shared and std::fstream with Aws::MakeShared and Aws::FStream. No other changes are involved but we need to add dir_name.c_str() as second argument for Aws::FStream. dir_name has value ".".

We tested it again to be sure, using our working example and following the steps I told you.

These are our cmake arguments for building the SDK:

```
cmake ../aws-sdk-cpp-master/ -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" -DCURL_INCLUDE_DIR=~/curl-7.37.0/include -DSTATIC_LINKING=0
```

Please note this issue isn't blocking. Take as long as you need to check this.

**Comment by bretambrose** [comment] 2017-01-19 21:12
I think I see what the problem is:

Aws::MakeShared is not a drop-in replacement for std::make_shared.  Aws::MakeShared takes an additional string argument (allocation_tag) that allows custom allocation systems to add human-readable context to individual allocations.  This is the first and only required parameter to Aws::MakeShared.  All further parameters are forwarded to the template type's constructor.  In retrospect, we could have made the allocation tag a template parameter of type const char* with a sensible default, but it's too late for that now.

If you add dir_name.c_str() as the second parameter to the MakeShared call you will end up with an invalid file.  Sadly, submitting an invalid file will just give you an empty object in S3 rather than giving you a client-side error.  We might consider adding custom logic to perform this validation, but as it stands, an invalid stream comes across as a file of size zero from the request payload point-of-view.

So anyways, if I take your code sample and change the fstream line as follows:

    auto input_data = Aws::MakeShared<Aws::FStream>("FStreamAllocation", key_name.c_str(), std::ios_base::in);

then everything continues to work for me.

Obviously you're welcome to use Aws::MakeShared as you want, but its original intent was to function as a funnel for all in-SDK memory allocation.  In retrospect, I maybe should have made it private since, unlike the Aws STL types, it is not a drop-in replacement due to the allocation tag parameter.

**Comment by singku** [comment] 2019-03-24 01:21
This should have been fixed in the official example

**Closed by singku** 2019-03-24 01:21 UTC
Labels: help wanted
