### ISSUE TITLE
URL encoding is broken when the locale is Japanese

### ISSUE THREAD

**Issue by yamasakia** [aws/aws-sdk-cpp#824] opened 2018-03-14 03:49 UTC
I encountered issue that my program cannot download S3 objects which have Japanese key name. 
I looked into it, and I noticed the URL is broken when the locale is Japanese. You can confirm by adding following code to TestGetRFC3986URLEncodedPath in aws-cpp-sdk-core-tests\http\URITest.cpp:
```C++
// 日本 in UTF-8 hex notation
uri = "https://test.com/\xE6\x97\xA5\xE6\x9C\xAC";
std::setlocale(LC_ALL, "Japanese");  // test is passed when "C"
EXPECT_STREQ("/%E6%97%A5%E6%9C%AC", URI::URLEncodePathRFC3986(uri.GetPath()).c_str());
```

The main cause is std::isalnum. It depends on current locale. You should not use such kind of functions in this SDK.

### What platform/OS are you using?
Windows 10

### What compiler are you using? what version?
Visual Studio 2017 Update 6

**Comment by wps132230** [comment] 2018-03-15 18:09
Hi, thank you for reporting it to us.
To download/upload s3 objects with Japanese key name, you can follow these examples:
- GetObject: https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/get_object_unicode.cpp
- PutObject: https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/put_object_unicode.cpp

**Comment by yamasakia** [comment] 2018-03-16 08:21
@wps132230 Thank you for the examples.

You added an enhancement label, but this is a regression by commit da76318.
https://github.com/aws/aws-sdk-cpp/commit/da7631823f9778a2c5b96aba27b684acea7c75b3

**Comment by marcomagdy** [comment] 2018-08-23 16:34
Tested uploading/downloading and copying s3 objects with Japanese & Chinese key names and I'm unable to reproduce the problem.
We don't set the C locale to anything and in our testing the operations work as expected.
Please provide a repro sample if you're still encountering the problem.

**Comment by yamasakia** [comment] 2018-08-27 07:49
@marcomagdy I can reproduce this issue with 1.5.23.

I attached sample code. Before run the program, please upload "日本.txt" file to your bucket.

[GetObject.zip](https://github.com/aws/aws-sdk-cpp/files/2322855/GetObject.zip)

This program tries to download "日本.txt" file twice. First time, LC_ALL is set "C". Second, LC_ALL is set "Japanese". Both cases should be successful, but the second one will fail.

**Comment by yamasakia** [comment] 2018-08-30 05:58
@marcomagdy Could you reopen this issue?

**Comment by marcomagdy** [comment] 2018-08-30 16:47
The SDK assumes utf8 in all of its strings. And since C++ doesn't have utf-8 strings, the idiomatic way to do that is by using arrays of `char`. When you set the locale to Japanese, you break this assumption and that's why you see the broken behavior.

I'm happy to re-open this issue if there is a solution to accommodate all the different locales.

**Comment by marcomagdy** [comment] 2018-08-30 17:05
The only thing I could thing of is replacing [`isalnum`](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/http/URI.cpp#L128)  with something like:
```cpp
for(unsigned char c : segment) 
    //if(std::isalnum(c)) // §2.3 unreserved characters
    if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c >= '0' && c <= '9')
    {
        ss << c;
        continue;
    }
```
I'll have one of my teammates try that and update this ticket accordingly.

**Comment by marcomagdy** [comment] 2018-10-18 20:50
Working on it. Will have it merged this week

**Comment by marcomagdy** [comment] 2018-12-13 19:55
@yamasakia  v1.7.18 addresses this issue. We've replaced the locale-sensitive functions with ASCII only versions. I've run your repro program successfully.
Apologies that it took longer that I anticipated.
Let us know if you're still having problems.

**Closed by marcomagdy** 2018-12-13 19:55 UTC
Labels: bug
