### ISSUE TITLE
S3 crt client doesn't pick up the default region

### ISSUE THREAD

**Issue by dhananjays** [aws/aws-sdk-cpp#1768] opened 2021-09-09 06:41 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
S3-crt client doesn't automatically get the region unlike the S3 client which automatically fetches region (using the chain of AWS_DEFAULT_REGION -> profile -> instance metadata). The user is forced to provide the correct region when creating the s3-crt client

**SDK version number**
1.9

**Platform/OS/Hardware/Device**
EC2 Linux instance

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
Create S3 client without setting region in the client config. It automatically picks up the default region from the profile/instance metadata (This is as expected from version 1.8 as mentioned here - https://aws.amazon.com/blogs/developer/aws-sdk-for-c-version-1-8-developer-preview/)

Create S3-crt client without setting region in the client config. It does not pick the default region as expected.

**Expected behavior**
S3-crt client should automatically pick up the default region as done by the S3 client

**Comment by KaibaLopez** [comment] 2021-09-09 22:44
Hi @dhananjays ,
So, it seems like you've figured out the workaround , but for the record this behavior is not expected of the s3-crt default constructor. 

The s3-crt default provider chain is reduced to make it faster to go through, and it will only check for the region in the environment variable, the profile in the config file or the one hard coded.
Having said that, this could be a feature request, but I can't make any promises on when we could work on it.

**Comment by grrtrr** [comment] 2022-03-19 15:11
Here is how we back-ported that in our code, since we ran into the same issue: the CRT does not pickup `AWS_{,DEFAULT_}REGION`:
```c++
        Aws::S3Crt::ClientConfiguration config;
        // ...
        config.region = []() -> Aws::String {
            // Return the configured AWS region, using us-east-1 as fallback. This is normally part
            // of Aws::Client::ClientConfiguration, but is not implemented for the S3CrtClient.
            Aws::String region = os::getenv("AWS_DEFAULT_REGION");
            if (!region.empty()) {
                return region;
            }

            region = os::getenv("AWS_REGION");
            if (!region.empty()) {
                return region;
            }

            // The profile may also contain a region value.
            if (Aws::Config::HasCachedCredentialsProfile("default")) {
                region = Aws::Config::GetCachedCredentialsProfile("default").GetRegion();
                if (!region.empty()) {
                    return region;
                }
            }
            return Aws::Region::US_EAST_1;
        }();
```

**Comment by grrtrr** [comment] 2022-03-19 20:20
The problem is also resolved by #1884.

**Comment by jmklix** [comment] 2024-05-03 17:56
Merged: https://github.com/aws/aws-sdk-cpp/pull/2098

**Closed by jmklix** 2024-05-03 17:56 UTC
Labels: feature-request, p2

**Comment by grrtrr** [comment] 2024-05-03 18:49
Thank you.
