### ISSUE TITLE
Compile Error using GCC 9.0.1

### ISSUE THREAD

**Issue by kanzah** [aws/aws-sdk-cpp#1176] opened 2019-06-21 19:23 UTC
### What platform/OS are you using?
AWS EC2 - Ubuntu 18.04.2

### Which version of the SDK?
1.7.125

### What compiler are you using? what version?
gcc (GCC) 9.1.0

### What are your CMake arguments?
-DBUILD_ONLY="s3;transfer;sqs" 
-DCUSTOM_MEMORY_MANAGEMENT=0 
-DCPP_STANDARD=17

### Can you provide a TRACE level log? (sanitize any sensitive information)
```
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.7.125
-- Configuring done
-- Generating done

[  4%] Performing build step for 'AwsCCommon'
[ 46%] Built target aws-c-common
[ 48%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/test_runner.c.o
In function ‘lowercase’,
    inlined from ‘main’ at ~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c:1234:11:
~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c:1186:3: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
 1186 |   strncpy(new_string, string, stringSize);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c: In function ‘main’:
~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c:1180:32: note: length computed here
 1180 |   stringSize = CM_CAST(size_t, strlen(string) + 1);
      |                                ^~~~~~~~~~~~~~
~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c:245:36: note: in definition of macro ‘CM_CAST’
  245 | #define CM_CAST(TYPE, EXPR) (TYPE)(EXPR)
      |                                    ^~~~
In function ‘lowercase’,
    inlined from ‘main’ at ~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c:1237:17:
~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c:1186:3: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
 1186 |   strncpy(new_string, string, stringSize);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c: In function ‘main’:
~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c:1180:32: note: length computed here
 1180 |   stringSize = CM_CAST(size_t, strlen(string) + 1);
      |                                ^~~~~~~~~~~~~~
~/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build/tests/test_runner.c:245:36: note: in definition of macro ‘CM_CAST’
  245 | #define CM_CAST(TYPE, EXPR) (TYPE)(EXPR)
      |                                    ^~~~
cc1: all warnings being treated as errors
tests/CMakeFiles/aws-c-common-tests.dir/build.make:62: recipe for target 'tests/CMakeFiles/aws-c-common-tests.dir/test_runner.c.o' failed
make[5]: *** [tests/CMakeFiles/aws-c-common-tests.dir/test_runner.c.o] Error 1
CMakeFiles/Makefile2:1020: recipe for target 'tests/CMakeFiles/aws-c-common-tests.dir/all' failed
make[4]: *** [tests/CMakeFiles/aws-c-common-tests.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/AwsCCommon.dir/build.make:111: recipe for target 'build/src/AwsCCommon-stamp/AwsCCommon-build' failed
make[2]: *** [build/src/AwsCCommon-stamp/AwsCCommon-build] Error 2
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/AwsCCommon.dir/all' failed
make[1]: *** [CMakeFiles/AwsCCommon.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMakeLists.txt:193 (message):
  Failed to build third-party libraries.
```

**Comment by KaibaLopez** [comment] 2019-06-21 23:28
Hi @kanzah, thanks for pointing this out to us, it looks like this problem happens specifically on gcc/g++ 9.1 compiler's Release builds. I'll have to take a deeper look into it to get to the root cause, but if you need a quick work around here's a couple things you could try:
1. Try running with a previous gnu compiler: On 7.4 the build completes with your given parameters.
2. You could run on Debug mode by adding -DCMAKE_BUILD_TYPE=Debug to your cmake arguments.

**Comment by KaibaLopez** [comment] 2019-06-24 21:31
Hi @kanzah, 
The error is related to cmake version with gcc versions 8.1 and later.
It was fixed on https://github.com/Kitware/CMake/commit/3af0438b4bccc599792f61a9f4be81b4bb36c3e3 
Update your cmake the latest version (as of this comment 3.15.0-r2) and the error should go away.

**Closed** 2019-06-25 00:33 UTC
Labels: guidance
