### ISSUE TITLE
vcpkg doesn't install all of aws-sdk-cpp

### ISSUE THREAD

**Issue by SCalwas** [aws/aws-sdk-cpp#1044] opened 2019-01-17 03:28 UTC
From a Windows command prompt:
```
$ vcpkg install aws-sdk-cpp:x86-windows
The following packages will be built and installed:
    aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows
...
```
The build proceeds and successfully builds those four packages, but I wanted to build ALL the packages in the SDK. How to do that?

**Comment by singku** [comment] 2019-01-17 04:55
Duplicate of #1036

**Closed** 2019-01-17 04:56 UTC
