### ISSUE TITLE
Multi-part upload behind a load-balanced s3 hosts does not work

### ISSUE THREAD

**Issue by kedarX** [aws/aws-sdk-cpp#932] opened 2018-08-08 11:16 UTC
### What platform/OS are you using?
CentOS 7

### What compiler are you using? what version?
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

### What's your CMake arguments?
cmake .. -DBUILD_ONLY="core;s3" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/kedar/aws-sdk-cpp-1.4.92/ -DBUILD_SHARED_LIBS=ON -DOPENSSL_INCLUDE_DIR=/home/kedar/openssl-1.0.2k/include -DCURL_INCLUDE_DIR=/home/kedar/curl-7.53.1/include -DENABLE_TESTING=OFF

### Can you provide a TRACE level log? (sanitize any sensitive information)

Transfer client seems to work fine with single s3 host; however, if multiple host are behind a load balancer (with round-robin policy); aws cpp transfer client creates multiple PUT requests for same part number on every host. It continues infinitely to the point that an ERROR callback is received and upload fails with `status: FAILED`. 

s3cmd works on same environment; where in different part numbers are PUT on different host behind LB only once.

@JonathanHenson

**Comment by JonathanHenson** [comment] 2018-08-08 14:02
For more context, is this happening as a result of retries? (This would be expected behavior if so)

Also, since you know so much about the backend architecture, I’m assuming you’re either on the S3 team or are talking about some sort of S3 compatible storage you are hosting privately? In other words, how do you know what host you’re hitting?

**Comment by crusader-mike** [comment] 2018-08-13 22:18
@kedarX Any additional info in the logs on why it was "Unable to connect"? I had this error due to following reasons:
- SSL certificate problems (including one where server was choosing cipher Windows had problems implementing properly) -- see if problem can be reproduced using HTTP, blacklist that cipher
- race condition in libNSS (used instead of libopenssl by default libcurl on CentOS) -- had to build my own libcurl
- failed DNS lookups to due to the way Microsoft tcp stack handles ARP requests -- pre-warm DNS server, increase request timeout to 11 secs (to give room for 2nd DNS request)

**Comment by kedarX** [comment] 2018-08-14 03:57
@crusader-mike I believe none of the above were the possible issues in my case. The upload works fine when connected to single host (bypassing load balancer). One thing sets apart is, transfer manager sends the same part upload across all host behind the load-balancer. There also a large number of upload progress callbacks (guess that's expected); however, eventually, the progress times out and s3 storage responds back with "Unable to connect" error. See that few parts do upload successfully, as seen from above log snippets

**Comment by crusader-mike** [comment] 2018-08-14 06:32
No probs, I don't know much about specifics of your setup (load balancer + transfer manager), thought my past experience may help. Usually, 'unable to connect' error happens on client side and is accompanied with additional errors that provide some insight,

**Comment by kedarX** [comment] 2018-08-16 02:30
@crusader-mike that does help; I will keep your inputs on my list while debugging this problem. @JonathanHenson @marcomagdy any inputs on above detailed logs. I believe the handling of intermediate request across multiple hosts behind a LB is something that does not work with transfer manager yet?

**Comment by marcomagdy** [comment] 2018-08-16 19:08
What kind of load balancer are you using? This seems like it might be a bug in your LB. The SDK will resolve the hostname (once) to a single ip address and connect to it, potentially multiple times. That ip address will be your LB address. It's your LB responsibility then to forward that tuple of ip/port to a single host. The SDK doesn't know anything about your server side setup and doesn't do any actions based on that.

I'm closing this issue, but you're welcome to continue to the discussion.

**Closed by marcomagdy** 2018-08-16 19:08 UTC

**Comment by kedarX** [comment] 2018-08-18 02:27
@marcomagdy I thought the same; However, wondering how come the same backend setup worked with s3cmd command line utility. It did upload multiple parts across multiple backend hosts.
