### ISSUE TITLE
1.9.379 prefetch_crt_dependency.sh fetch the wrong crt dependency

### ISSUE THREAD

**Issue by Smith-Cruise** [aws/aws-sdk-cpp#2512] opened 2023-05-25 06:58 UTC
### Describe the bug

I use `prefetch_crt_dependency.sh` to fetch crt, can't compile crt successfully. But if using the `git clone xxx` way, I can compile successfully. So I think maybe `prefetch_crt_dependency.sh` fetch the wrong version of crt.

### Expected Behavior

Compile successfully.

### Current Behavior

Compile failed.

### Reproduction Steps

`sh prefetch_crt_dependency.sh`, then compile it.

### AWS CPP SDK version used

1.9.379

### Compiler and Version used

gcc11

### Operating System and version

ubuntu22.04

**Comment by Smith-Cruise** [comment] 2023-05-25 06:58
![9da14440-b15c-4c9c-8003-06401311906a](https://github.com/aws/aws-sdk-cpp/assets/18729228/05d70774-f47c-42cb-a33c-6ad925bdc500)

**Comment by yasminetalby** [comment] 2023-05-25 13:46
Hello @Smith-Cruise ,

Thank you very much for your submission.
I am not able to reproduce this issue when using the latest version of the AWS C++ SDK (v1.11.86)
According to your submission, you are using v1.9.379 of the aws-cpp-sdk. Could you please update to the latest version of the SDK and see if this issue still occurs or is there a specific reason for you to be using an older version of the SDK?

Thank you very much for your time and collaboration.

Sincerely,

Yasmine

**Comment by Smith-Cruise** [comment] 2023-05-26 03:14
I know upgrade aws version can solve this problem, but I just kindly remainder tell you that `v1.9.379` has bug.

**Comment by yasminetalby** [comment] 2023-05-26 12:26
Thank you for your thoughtfulness @Smith-Cruise.,
This might help other users who encounter similar issues with older version of the SDK.

We do release new version of the C++ SDK regularly which contains bug fixes, new features and improvement.

For anyone encountering this issue, please make sure to upgrade to the latest version of the AWS C++ SDK. I will close this submission as this is not an ongoing issue.

Thank you very much for your time and feedback.

Sincerely,

Yasmine

**Closed** 2023-05-26 12:27 UTC
Labels: bug, response-requested
