### ISSUE TITLE
aws-sdk-cpp-1.11.323 curlcode：35 SSL connect error

### ISSUE THREAD

**Issue by txh1873749380** [aws/aws-sdk-cpp#2992] opened 2024-06-07 03:19 UTC
### Describe the bug

In the aws-sdk-cpp-1.11.323 version, `curlcode: 35 ssl connect error` occurred while verifying a small demo, and verifySSL was disabled.
Here is the demo code:
![截屏2024-06-07 10 46 26](https://github.com/aws/aws-sdk-cpp/assets/111034819/2ac87ee1-6aff-473a-b35e-ee9e7ea7f621)
![截屏2024-06-07 10 47 54](https://github.com/aws/aws-sdk-cpp/assets/111034819/658eee8f-1e6b-4972-b8a8-e5941a051f09)

### Expected Behavior

It is expected that the execution will be successful and the size will be calculated as follows:
<img width="550" alt="截屏2024-06-07 10 50 24" src="https://github.com/aws/aws-sdk-cpp/assets/111034819/051bb0b2-3fee-4879-99e9-eb0676b2879e">

### Current Behavior

![截屏2024-06-07 10 53 47](https://github.com/aws/aws-sdk-cpp/assets/111034819/e4ab52b8-858a-47fe-9ab9-350a31801872)

### Reproduction Steps

![截屏2024-06-07 10 46 26](https://github.com/aws/aws-sdk-cpp/assets/111034819/860f9c90-74c8-4a54-9dc7-0ae6330746d1)
![截屏2024-06-07 10 47 54](https://github.com/aws/aws-sdk-cpp/assets/111034819/fd6686f4-d954-4a61-8fd8-610b54732d7f)

### Additional Information/Context

demo g++ compilation command:
![截屏2024-06-07 11 03 19](https://github.com/aws/aws-sdk-cpp/assets/111034819/f08456c0-b387-46cb-8b93-9c2b380044f0)

### AWS CPP SDK version used

aws-sdk-cpp-1.11.323

### Compiler and Version used

g++ 8.3.1

### Operating System and version

Kernel :linux  Kernel version:5.14.21  x86_64 centos7

**Comment by jmklix** [comment] 2024-06-13 23:36
How are you building this sdk? and can you paste your code snippets in code block rather then in screenshots?

**Comment by txh1873749380** [comment] 2024-06-24 06:32
> How are you building this sdk? and can you paste your code snippets in code block rather then in screenshots?你是如何构建这个SDK的？你能把你的代码片段粘贴到代码块中而不是屏幕截图中吗？

`#include <aws/s3/S3Client.h>
#include <aws/core/Aws.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
#include <aws/transfer/TransferManager.h>
#include <aws/s3/model/HeadObjectRequest.h>
#include <aws/s3/model/HeadBucketRequest.h>
#include <iostream>
#include <fstream>

#include<sys/types.h>  /*提供类型pid_t,size_t的定义*/
#include<sys/stat.h>
#include<fcntl.h>

static const char* const ALLOCATION_TAG = "S3_HEADOBJECT";


int main(int argc, char* argv[]) {
  Aws::SDKOptions options;
  Aws::InitAPI(options);
  {
    // 自訂 S3 End Point
    const Aws::String endPoint = "172.16.10.115:9000";
    const Aws::String bucketName = "hcc-bucket";
    //const Aws::String objectName = "project_id_1";
    const Aws::String objectName = argv[1];
    const Aws::String region = "us-west-2";
    // 認證資訊
    const Aws::String accessKey = "minioadmin";
    const Aws::String secretKey = "minioadmin";
    bool using_virtual_address = false;


    // 建立 S3 Client
    Aws::Client::ClientConfiguration config;
    config.verifySSL = false;
    config.scheme = Aws::Http::Scheme::HTTP;
    config.region = region;

    //bool using_virtual_address = bucket_cfg.s3_uri_style == 0 ? true : false;
    Aws::Auth::AWSCredentials cred(accessKey, secretKey);

    auto s3Client = Aws::MakeShared<Aws::S3::S3Client>(
                 ALLOCATION_TAG,
                 cred,
                 config,
                 Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never,
                 using_virtual_address);
    s3Client->OverrideEndpoint(endPoint);

    // aws request
    Aws::S3::Model::HeadObjectRequest aws_req;
    aws_req.SetBucket(bucketName);
    aws_req.SetKey(objectName);

    Aws::S3::Model::HeadObjectOutcome aws_resp = s3Client->HeadObject(aws_req);
    if (aws_resp.IsSuccess()) {
        long long size_total = aws_resp.GetResult().GetContentLength();
        std::cout << "objectName:" << objectName << ", size:" << size_total << std::endl;
    } else {
        // has error
        auto err = aws_resp.GetError();
        std::cout << "head object error, objectName:"<< objectName << ", errno:" << (int)err.GetErrorType() << ", errmsg:" << err.GetMessage()<< std::endl;
    }
  }

  Aws::ShutdownAPI(options);
  return 0;
}`

**Comment by jmklix** [comment] 2024-06-27 16:37
Can you reproduce this error when using AWS s3 buckets? We can't guarantee that this sdk will work with third party buckets (i.e. minio). If you can reproduce this with an s3 bucket then we can take a closer look.

**Comment by txh1873749380** [comment] 2024-07-09 08:41
> Can you reproduce this error when using AWS s3 buckets? We can't guarantee that this sdk will work with third party buckets (i.e. minio). If you can reproduce this with an s3 bucket then we can take a closer look.

Okay, I'll give it a try

**Comment by txh1873749380** [comment] 2024-07-17 06:58
> > Can you reproduce this error when using AWS s3 buckets? We can't guarantee that this sdk will work with third party buckets (i.e. minio). If you can reproduce this with an s3 bucket then we can take a closer look.
> 
> Okay, I'll give it a try
> 
> 
> > 在使用AWS s3 bucket时，是否可以重现此错误？我们不能保证这个sdk将与第三方bucket（即minio）一起工作。如果你能用一个s3桶来复制这个，那么我们就可以仔细看看了。
> 
> 好吧，我试试

After our discussion, we want to support third-party libraries. Do you have any other solutions to solve this problem?

**Comment by txh1873749380** [comment] 2024-07-17 06:59
> > Can you reproduce this error when using AWS s3 buckets? We can't guarantee that this sdk will work with third party buckets (i.e. minio). If you can reproduce this with an s3 bucket then we can take a closer look.
> 
> Okay, I'll give it a try
> 
> 
> > 在使用AWS s3 bucket时，是否可以重现此错误？我们不能保证这个sdk将与第三方bucket（即minio）一起工作。如果你能用一个s3桶来复制这个，那么我们就可以仔细看看了。
> 
> 好吧，我试试

After our discussion, we want to support third-party bucket like ceph and minio. Do you have any other solutions to solve this problem?

**Comment by jmklix** [comment] 2024-07-17 17:34
This sdk doesn't officially support and third-party buckets like ceph and minio. If they do work with this sdk, that is great. But we only guarantee compatibility with AWS s3 buckets. If the root cause is because of an issue with a third-party bucket, then you would need to contact the third-party bucket to see if they would fix the problem. The other possibility is that this is a problem with this sdk. To show that we need to be able to reproduce the same error (`curlcode：35 SSL connect error`) while using an AWS s3 bucket.

You can also use the respective sdk's for third-party buckets if you're using third-party buckets. This might be your best solution if you want to use ceph and minio.

**Comment by txh1873749380** [comment] 2024-07-18 09:55
> This sdk doesn't officially support and third-party buckets like ceph and minio. If they do work with this sdk, that is great. But we only guarantee compatibility with AWS s3 buckets. If the root cause is because of an issue with a third-party bucket, then you would need to contact the third-party bucket to see if they would fix the problem. The other possibility is that this is a problem with this sdk. To show that we need to be able to reproduce the same error (`curlcode：35 SSL connect error`) while using an AWS s3 bucket.
> 
> You can also use the respective sdk's for third-party buckets if you're using third-party buckets. This might be your best solution if you want to use ceph and minio.
> 
> 
> 该sdk不正式支持ceph和minio等第三方桶。如果他们确实使用这个SDK，那就太好了。但我们仅保证与AWS s3桶的兼容性。如果根本原因是第三方存储桶的问题，那么您需要联系第三方存储桶，看看他们是否会解决该问题。另一种可能是这个sdk有问题。为了说明我们需要能够在使用AWS s3存储桶时重现相同的错误（`curlcode：35 SSL connect error`）。
> 
> 如果你使用的是第三方bucket，你也可以使用第三方bucket的相应sdk。如果你想使用ceph和minio，这可能是你最好的解决方案。



> This sdk doesn't officially support and third-party buckets like ceph and minio. If they do work with this sdk, that is great. But we only guarantee compatibility with AWS s3 buckets. If the root cause is because of an issue with a third-party bucket, then you would need to contact the third-party bucket to see if they would fix the problem. The other possibility is that this is a problem with this sdk. To show that we need to be able to reproduce the same error (`curlcode：35 SSL connect error`) while using an AWS s3 bucket.
> 
> You can also use the respective sdk's for third-party buckets if you're using third-party buckets. This might be your best solution if you want to use ceph and minio.

According to our testing of aws bucket, we can get the expected effect, but we still hope to get the support of a third-party bucket, and I wonder whether your company will make compatibility requirements in the future.

**Comment by jmklix** [comment] 2024-07-18 18:36
Sorry, but we don't plan to support third-party buckets at any point in the future. Closing this issue

**Closed by jmklix** 2024-07-18 18:36 UTC
Labels: bug, third-party, closing-soon, response-requested, p3
