### ISSUE TITLE
UE4/Android ClientConfiguration destructor crash

### ISSUE THREAD

**Issue by AlexGroszq** [aws/aws-sdk-cpp#1244] opened 2019-09-24 10:01 UTC
I've built aws-sdk-cpp as shared library to use .so, because that's what best supported in UnrealEngine 4. Packaging process doesn't return any errors, but when I successfuly instantiate GameLiftClient with custom configuration it crashed after ClientConfiguration destructor is called. What am I doing wrong? Do I need to pass another argument?

### What platform/OS are you using?
OS: MacOS Mojave 10.14.6
Target: Android

### Which version of the SDK?
3.15.2

### What compiler are you using? what version?
LLVM/Clang/libc++ (clang-1000.11.45.5)

### What are your CMake arguments?
-DTARGET_ARCH=ANDROID -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS=ON -DNDK_DIR=/Users/alexkaczmarek/Downloads/android-ndk-r19

### Can you provide a TRACE level log? (sanitize any sensitive information)
```
09-16 16:58:59.448 15976 15976 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfffffffffffffff8
09-16 16:58:59.448 15976 15976 F DEBUG   :     x0  ffffffffffffffe8  x1  00000073e91f6000  x2  00000073e9000000  x3  0000000000000003
09-16 16:58:59.448 15976 15976 F DEBUG   :     x4  00000000000001f6  x5  0000007401aa84e3  x6  2f2f3a7370747468  x7  7466696c656d6167
09-16 16:58:59.448 15976 15976 F DEBUG   :     x8  fffffffffffffff8  x9  00000074bf0c8800  x10 00000000f8b05a9f  x11 0000000000000000
09-16 16:58:59.448 15976 15976 F DEBUG   :     x12 6f7a616d612e312d  x13 6d6f632e7377616e  x14 00000073e8200000  x15 0000000000000000
09-16 16:58:59.448 15976 15976 F DEBUG   :     x16 00000074bf133bb8  x17 00000074bf0c9620  x18 0000000005e72ef4  x19 0000007421468c50
09-16 16:58:59.448 15976 15976 F DEBUG   :     x20 0000007421469500  x21 000000741fb66c90  x22 0000007421468af0  x23 0000000000000000
09-16 16:58:59.448 15976 15976 F DEBUG   :     x24 0000007421468ba0  x25 0000007421468c60  x26 00000073fa43d3f8  x27 000000741fcc8f18
09-16 16:58:59.448 15976 15976 F DEBUG   :     x28 0000007421469570  x29 0000007421468990
09-16 16:58:59.448 15976 15976 F DEBUG   :     sp  0000007421468960  lr  000000741b7256d0  pc  000000741b726484
09-16 16:58:59.588 15976 15976 F DEBUG   : 
09-16 16:58:59.588 15976 15976 F DEBUG   : backtrace:
09-16 16:58:59.588 15976 15976 F DEBUG   :     #00 pc 00000000033e3484  /data/app/com.pixellegend.virtualist-N7zux-YwUXDGkoNqAVt7sA==/lib/arm64/libUE4.so (Aws::Client::ClientConfiguration::~ClientConfiguration()+852)
```

**Comment by singku** [comment] 2019-09-26 18:25
Would you please share your code?

**Comment by AlexGroszq** [comment] 2019-09-30 09:04
@KaibaLopez Which part of the code do you want me to share? Build.cs or loading module?

**Comment by KaibaLopez** [comment] 2019-10-01 17:01
Hi @AlexGroszq, both would be helpful, but since this is not an error on build, if you can provide the simplest code sample to reproduce this error, that would save us a lot of time.

**Comment by AlexGroszq** [comment] 2019-10-03 08:42
@KaibaLopez Here are code examples of what I am doing.

Fragment of Build.cs for GameliftLibrary:

![obraz](https://user-images.githubusercontent.com/55738962/66111743-c94d8a00-e5c9-11e9-9518-8d1a7d8c118c.png)

GameLiftClientSDK_UPL:

![obraz](https://user-images.githubusercontent.com/55738962/66111860-074aae00-e5ca-11e9-8018-17b8d03c0c56.png)

Same thing is done for AWS Core part. No brainer here.

Here is the part, which causes the fatal error:

![obraz](https://user-images.githubusercontent.com/55738962/66112024-5bee2900-e5ca-11e9-9704-55b03ea0f22c.png)

I have already debugged it. It turns out, that method from line 38th is called successfuly (I checked all the lines in Internal_InitGameLiftClientSDK). After GC is collecting Aws::Client::Configuration class it crashes with fatal error.

**Comment by KaibaLopez** [comment] 2019-10-03 23:50
Hi @AlexGroszq, this seems to be an implementation and not an sdk problem, so not much I can help you with here... 
But just in case, can you try to just do:
`delete GameLiftClient;`
and see if you get the error on that destructor call?

**Comment by AlexGroszq** [comment] 2019-10-04 13:19
Hello @KaibaLopez I tried what you told me to do, and I am also getting the same crash as before.

**Comment by AlexGroszq** [comment] 2019-10-11 11:30
@KaibaLopez One week later and no response from you?

**Comment by AlexGroszq** [comment] 2019-10-14 10:59
@KaibaLopez Hello, do you know anyone who would not ignore me? I know you (as amazon) are not officially supporting Epic's engine in terms of client API, but at least you could response to my comments in this issue.

**Comment by KaibaLopez** [comment] 2019-10-14 17:59
I'm sorry for the lack of response last week @AlexGroszq , the truth is I have not made significant progress with your issue so I have no real udpate for you. From the looks of it, this is not a problem with the SDK itself, so it is lower priority for us.
Now, because this is a kind of specific issue to your implementation you're having. I'd say try forums like stackoverflow or Unreal Engine. 
While this is an open source project and ideally we'd have contributors from the community help out when possible, you'll probably find more community support/responses from one of those sites.
As of now, all I can recommend for you is trying not to use standard pointers, as they can be tricky to delete.

**Comment by JonathanHenson** [comment] 2019-10-14 19:08
Just a hunch, are you calling Aws::InitAPI() anywhere in your code?

**Comment by AlexGroszq** [comment] 2019-10-15 08:49
@JonathanHenson 

Hello Jonathan,  I am calling Aws:InitAPI(). Otherwise I was getting an error in Aws::Utils::Crypto::CreateSha256Implementation()

**Comment by KaibaLopez** [comment] 2019-11-11 22:41
@AlexGroszq , I'm truly sorry I was never able to solve your issue, but because it is not really reproducible, I don't have anything else to do about it so I'll be closing it, again I recommend you take this to forums in hopes to get more community support for implementation kind of issues.

**Closed by KaibaLopez** 2019-11-11 22:41 UTC
Labels: response-requested

**Comment by concubicycle** [comment] 2022-04-12 07:47
Hey, I had some similar issue with a crash in destructor of `Aws::Client::ClientConfiguration`. It seems to be solved by making `Aws::Client::ClientConfiguration` static or global... go figure.
