### ISSUE TITLE
Could NOT find LibCrypto (missing: LibCrypto_LIBRARY) on amazonlinux

### ISSUE THREAD

**Issue by joscul** [aws/aws-sdk-cpp#1620] opened 2021-04-18 07:08 UTC
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Docker container amazonlinux:latest

**Describe the question**
I am trying to compile aws-sdk-cpp on the docker container amazonlinux:latest with this docker file:
```
FROM amazonlinux:latest

RUN yum update -y
RUN yum install -y gcc-c++ make cmake3 perl git libcurl-devel zip zlib-devel openssl-devel
RUN cd ~ ; \
    git clone https://github.com/aws/aws-sdk-cpp.git ; \
    cd aws-sdk-cpp ; \
    git submodule update --init --recursive ; \
    mkdir build ; \
    cd build ; \
    cmake3 .. -DBUILD_ONLY=s3 -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/out -DENABLE_TESTING=OFF -DBUILD_DEPS=ON ; \
    make ; \
    make install
```

And I am getting this output:
```CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibCrypto (missing: LibCrypto_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  crt/aws-crt-cpp/crt/s2n/cmake/modules/FindLibCrypto.cmake:61 (find_package_handle_standard_args)
  crt/aws-crt-cpp/crt/s2n/CMakeLists.txt:233 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/aws-sdk-cpp/build/CMakeFiles/CMakeOutput.log".
See also "/root/aws-sdk-cpp/build/CMakeFiles/CMakeError.log".```

**Comment by KaibaLopez** [comment] 2021-04-19 18:13
Hi @joscul, 
Yea this is reproducible in our side and are working on a fix, the problem seems to be specific to static libraries.
Thanks for pointing it out to us.

**Comment by KaibaLopez** [comment] 2021-05-03 18:52
Hi @joscul ,
Update: This should be fixed, please update to the latest version of the SDK and you should not be seeing this issue anymore.

**Closed by KaibaLopez** 2021-05-03 18:52 UTC
Labels: bug, guidance
