### ISSUE TITLE
S3: question about DataSentEventHandler and DataReceivedEventHandler 

### ISSUE THREAD

**Issue by mikewang2016** [aws/aws-sdk-cpp#378] opened 2016-12-12 03:21 UTC
Will these two functions be executed in single thread? or I have to do multithreading sync myself?

**Comment by JonathanHenson** [comment] 2016-12-12 05:45
they will be called from the thread executing the request. if you use the async api, it will already be in a new thread. You need to be mindful that you should not block inside the callback because that will affect the transfer speed of the request. If you need to do something time intensive in this callback, you should submit the task to your thread executor.

**Comment by mikewang2016** [comment] 2016-12-12 07:44
Thank you for your quick response. Here is my use case:

I want to access data before GetObjectCallable is complete. So, I register "DataReceivedEventHandler", and track current available data length as below:

_datalen = datalen + size_


My application will access the data buffer before "datalen".

So, in such case, I do not need add additional mutex lock around my code, right?

**Comment by bretambrose** [comment] 2016-12-13 17:15
Without an appropriate memory fence, I don't believe you will be able to guarantee that the buffer has the data before datalen is updated, even if the datalen update occurs "after" the buffer is written to in the code.  That is something you will need to add yourself in the callback.

**Comment by mikewang2016** [comment] 2016-12-14 07:01
Look at the code in function below:

_size_t CurlHttpClient::WriteData(char* ptr, size_t size, size_t nmemb, void* userdata)_

We can see that buffer is updated before "DataReceivedEventHandler" is called. And JonathanHenson has confirmed all that code are executed in signal thread (the thread making current request), so we are sure that "datalen" can always reflect the data size in the buffer.


My application will check "datalen" in another thread, but I will make sure it only access data which position is before "dataLen". 

Do you see any problem here?

**Comment by bretambrose** [comment] 2016-12-16 17:27
It's probably fine, assuming datalen is a std::atomic.  Based on my reading of http://en.cppreference.com/w/cpp/atomic/memory_order updating datalen should ensure (memory_order_seq_cst is the default for an atomic fetch_add) that the previous writes to the buffer are visible to your other thread given an update to datalen.

**Comment by JonathanHenson** [comment] 2016-12-27 20:17
"And JonathanHenson has confirmed all that code are executed in signal thread (the thread making current request), so we are sure that "datalen" can always reflect the data size in the buffer."

A note here, I wouldn't assume this, not because it isn't currently true, but because this is subject to change. I'm currently experimenting with going to a full async threading model, and won't be able to guarantee which thread this gets called on.

That said, please reopen if you are still having issues. Closing for now.

**Closed by JonathanHenson** 2016-12-27 20:17 UTC
Labels: question
