### ISSUE TITLE
How to cleanly build and deploy with all build dependencies

### ISSUE THREAD

**Issue by whiplash86** [aws/aws-sdk-cpp#1020] opened 2018-11-23 18:21 UTC
### What platform/OS are you using?

Windows 10, Debian 9.5

### What compiler are you using? what version?

Visual Studio 2017 15.9.0, gcc 7.3.0

### What's your CMake arguments?

-DBUILD_ONLY="core;s3" -DCPP_STANDARD=17

If I just follow the build steps provided in the documentation, the CMake configure step already clones and builds some AWS dependencies in the subfolder of my build directory, namely aws-c-common, aws-c-event-stream and aws-checksums. The problem is, that they get installed to a location nested inside my build folder as a default (<build_dir>/.deps/install). I also tried to provide a CMAKE_INSTALL_PREFIX which helps in that the dynamic libraries now end up in <install_dir>/lib. However this is still different from the top-level script which installs shared objects into <install_dir>/bin. So how is this supposed to work cleanly? I'd like to be able to build and install with a single click, not having to move around files or provide two different yet similar system paths. As a side-effect, the clean vanilla build without providing any flags to CMake whatsoever fails for this exact same reason because when the unit tests are autorun and link to these dependencies, they can't find the shared libraries in the system path.

**Comment by whiplash86** [comment] 2018-11-26 08:55
likely related: #1019

**Comment by jni2000** [comment] 2018-11-26 16:36
I think the following commands will build all (this is for ubuntu, though)

cmake ~/workspace/aws/aws-sdk-cpp

OR
cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=ON

**Comment by whiplash86** [comment] 2018-11-26 18:09
Yes, building is not the problem. The build itself also succeeds with core, s3 only. The problem is that the output of the dependencies will be installed into /usr/local/lib instead of /usr/local/bin so I manually have to provide this path to all dependant executables and can't configure the build so it installs everything consistantly in one single output directory. Same story on windows.

**Comment by jni2000** [comment] 2018-11-26 20:05
Ok, good to know that your building succeeded. Do you by any chance know where to find libaws-checksums.so ? I Googled a lot and found no clues. I always have the following errors when make.

./aws-cpp-sdk-core-tests: error while loading shared libraries: libaws-checksums.so: cannot open shared object file: No such file or directory
aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:1127: recipe for target 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests' failed

Thanks.

**Comment by webbnh** [comment] 2018-11-26 21:14
Hi @jni2000, I'm having a problem similar to yours (only, in my case, it's `libaws-c-event-stream` which is missing -- it was built when I built the AWS SDK, but it was installed in `.deps/install/lib/` instead of in `/usr/local/lib`).  Since that component is built during the build _configuration_, I'm having trouble finding the lever which controls where it gets put.

**Comment by jni2000** [comment] 2018-11-26 21:52
Thanks @webbnh. I have seen a similar problem in another try. Thanks for sharing. I will continue work on it and share with you about my findings if progress is made. Thanks again.

**Comment by wps132230** [comment] 2018-11-26 23:46
Starting from 1.7.0, C++ SDK need dependencies on [aws-c-common](https://github.com/awslabs/aws-c-common), [aws-checksums](https://github.com/awslabs/aws-checksums) and [aws-c-event-stream](https://github.com/awslabs/aws-c-event-stream).

It's just like any other dependencies such as curl, openssl, we have to build, install and link to these libraries. The differences are C++ SDK will build and install aws-* libraries with some default behavior: aws-* will be installed under `.deps/install/lib` by default with cmake option `BUILD_DEPS` turned on.

If you want to install aws-* libraries to some specified location, you can download the source, build and install it. And when building the SDK, turn off the cmake option `BUILD_DEPS` and provide the aws-* libraries location with `CMAKE_PREFIX_PATH`.
Here is an example:
1. Download, build and install aws-c-common
```bash
git clone https://github.com/awslabs/aws-c-common
cd aws-c-common
# This is the commit we've tested that works with C++ SDK.
git checkout a9380a43ab3762
mkdir build && cd build
# without CMAKE_INSTALL_PREFIX, it will be installed to /usr/local/lib by default.
cmake .. -DCMAKE_INSTALL_PREFIX=~/aws_deps -DBUILD_SHARED_LIBS=ON
make -j 8
make install
```
2. Download, build and install aws-checksums
```bash
git clone https://github.com/awslabs/aws-checksums
cd aws-checksums
git checkout 8db7ac89d232b
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=~/aws_deps -DBUILD_SHARED_LIBS=ON
make -j 8
make install
```
3. Download, build and install aws-c-event-stream
```bash
git clone https://github.com/awslabs/aws-c-event-stream
cd aws-c-event-stream
git checkout 40dc42f47f3
mkdir build && cd build
# aws-c-event-stream has dependencies on aws-c-common and aws-checksums
cmake .. -DCMAKE_INSTALL_PREFIX=~/aws_deps -DCMAKE_PREFIX_PATH=~/aws_deps -DBUILD_SHARED_LIBS=ON
make -j 8
make install
```
4. Build C++ SDK
```
git clone https://github.com/aws/aws-sdk-cpp.git
cd aws-sdk-cpp
mkdir build && cd build
cmake .. -DBUILD_ONLY=s3 -DBUILD_DEPS=OFF -DCMAKE_PREFIX_PATH=~/aws_deps
make -j 8
```
Then you can try `aws-cpp-sdk-core-tests` or `aws-cpp-sdk-s3-integration-tests`.

**Comment by webbnh** [comment] 2018-11-27 01:14
Hi @wps132230, thanks for responding.

The problem that I hit was that I followed the installation instructions in the AWS SDK `README.md` file but got this result when I tried to run my code:
```
dyld: Library not loaded: @rpath/libaws-c-event-stream.dylib
  Referenced from: /usr/local/lib/libaws-cpp-sdk-sns.dylib
  Reason: image not found
```

The reason is that, I did not have the dependencies installed in my environment, and nothing indicated that I needed to install them separately, so, when I built the AWS SDK, it, of course, put the `libaws-c-event-stream` shared library in `.deps/install/lib`, and then, when I did the `make install`, it installed `libaws-c-event-stream.a` but not ``libaws-c-event-stream.dylib` in `/usr/local/lib`.

[The blame for my subsequent difficulties I lay at the feet of CMake, for not overriding its cached value when I specified `-DCMAKE_INSTALL_PREFIX` -- once I removed the build directory (and the cache) and restarted from scratch, then everything worked fine (or, at least, it got me on to the next problem which is probably in my code...).]

So, it seems to me that there is a bug, here, either in the documentation or in the AWS SDK installation script (or both...):  nothing told me to first install the SDK's dependencies, and, in fact, I was able to build the SDK without them installed; and, the installation installed some of the dependencies when it installed the SDK build results...just not _all_ of them (i.e., it installed the archives but not the shareables).

I'm amazed that no one else has fallen into this trap!

**Comment by whiplash86** [comment] 2018-11-27 09:44
also possibly related: #929

**Comment by jni2000** [comment] 2018-11-27 20:14
@whiplash86 @wps132230 Thanks a lot indeed to both of you for helping resolving my issues reported in this ticket. Following the procedure building aws-c-common, aws-checksums and aws-c-event-stream and install them, the build and install of aws-cpp-sdk are successful. The only point I would like to echo is what @whiplash86 had pointed out about the install location. I have to do manual copying of them to make them visible. 

The issue is resolved. Thanks.

**Comment by silcowitz** [comment] 2018-11-29 09:40
@wps132230 

I just did a clean checkout of aws-sdk-cpp and build it with 

cmake .. -DBUILD_ONLY="sqs;s3" -DENABLE_TESTING="OFF"
sudo make -j 8 install

Then later when building my application, i get this cmake output:

```
-- Found AWS SDK for C++, Version: 1.7.8, Install Root:/usr/local, Platform Prefix:, Platform Dependent Libraries: pthread;crypto;ssl;z;curl
-- Components specified for AWSSDK: sqs;s3
-- Try finding aws-cpp-sdk-core
CMake Error at /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  By not providing "Findaws-c-event-stream.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "aws-c-event-stream", but CMake did not find one.
```

Reading the posts here, it seems that this is actually what is expected, since we're now supposed to manually build aws-c-* dependencies?  And the cmake files that aws-sdk-cpp install on your system, is broken until you do?

**Comment by whiplash86** [comment] 2018-11-29 14:01
@silcowitz I don't think compiling all dependencies separately should be necessary. I guess what happens is that by not providing a CMAKE_INSTALL_PREFIX to the sdk build, it falls back to the default installation directory for the dependencies which is not in the default search path for other programs. Therefore the appropriate CMake find configs of the dependencies can't be found. Can you try to rebuild with i.e. -DCMAKE_INSTALL_PREFIX=/usr/local and see if that works?

**Comment by silcowitz** [comment] 2018-11-29 14:17
@whiplash86 
I tried and that fails because cmake is not being run with sudo/root privileges, and so it can't install to that location. I guess you could run it with sudo, but isn't that a bit weird?  Then everything in the build dir will be root.root owned. Normally it seems better to reduce the sudo to make install. 

So i tried again with everything under sudo, and it now works, so thanks :)  

However, surely there must be a way to make this play out more nicely?

**Comment by whiplash86** [comment] 2018-11-29 14:48
@silcowitz This is probably a more unix-specific question and I'm by no means an expert on that but to me it seems like /usr is still a system-wide location shared by all users so being allowed to only install there with root priviledges (and having root as owner) doesn't seem unreasonable to me. You can ofc install into a non-standard location w/o root access but then you obviously have to provide these paths to your applications because how should they know where your dependencies were installed?

Just out of curiosity: What happens when you run your executable now? Do you also get an error because one of the AWS dependency .so can't be loaded or does this work for you?

**Comment by silcowitz** [comment] 2018-11-29 15:24
It does work now, so that's good, no problems there :)  I just had to run everything as root, and use the DCMAKE_INSTALL_PREFIX=/usr/local as you pointed out. 

It's just that, why isn't everything just a normal cmake project, with one cmake step, one build step and one install step? can't that be accomplished somehow? Now, cmake is doing a full setup, build AND install of some sub projects during the cmake setup step, which seems very complicated?

**Comment by webbnh** [comment] 2018-11-29 17:09
Yes, it struck me as weird, as well, that the AWS SDK build was _building_ its dependencies during the _*configuration*_ step.  I would have expected it would configure the dependencies as subprojects (etc.) and then they would be built prior to building the SDK itself, during the `make` invocation.

**Comment by marcomagdy** [comment] 2018-11-29 21:32
>Yes, it struck me as weird, as well, that the AWS SDK build was building its dependencies during the configuration step.

I agree that this is less than idea, but it is necessary for `find_package(<deps name>)` to work during the configuration step _of the SDK_.

If we build the dependencies during the build step of the SDK, then the configuration step will fail to find those dependencies.

**Comment by whiplash86** [comment] 2018-11-30 09:54
I just found out that my executable is able to locate the SDK's main SOs but not the dependencies even though they both reside in /usr/local/lib. That is super weird and I have no idea why this is but if I run ldconfig before everything, it works.

On Windows however, the problem still persists. If you have a look at one of the dependency CMake scripts inside <build_dir>/.deps/build/AwsCCommon/ it contains these lines:

```
set(LIBRARY_DIRECTORY ${CMAKE_INSTALL_PREFIX}/lib)

install(TARGETS ${CMAKE_PROJECT_NAME}
    EXPORT ${CMAKE_PROJECT_NAME}-targets
    ARCHIVE DESTINATION ${LIBRARY_DIRECTORY}
    LIBRARY DESTINATION ${LIBRARY_DIRECTORY}
    RUNTIME DESTINATION ${LIBRARY_DIRECTORY})
```

so it obviously hardcores <install_dir>/lib as output folder for the dependency dlls. The top-level build script however installs its DLLs into <install_dir>/bin. So how is this inteded to work? I don't think providing two different search paths to the loader is the intended solution and as stated above breaks all build tests because they require the dependency DLLs being visible to the loader.

@marcomagdy You can have a look at grpc. I think they solved this quite nicely because they only try to find their dependencies if you select them as being external packages. Otherwise they are included as a CMake/git submodule and set as a normal dependency within the build itself. Your approach makes it quite awkward to use the CMake GUI on Windows for example where you have to configure once to create an initial CMake cache. This however will result in all dependencies being build in the default location and if you'd like to rebuilt them with a different INSTALL_PREFIX they won't because the build system doesn't detect any changes. So you have to manually clean the build output.

**Comment by silcowitz** [comment] 2018-11-30 10:14
@whiplash86  @marcomagdy  @webbnh 

It seems that the more clean way of going about this, is to include the aws-c-* dependencies as subprojects. and include a cmake option to disable building the aws-c-* subprojects, for those (very few?) people that somehow already have these dependencies build and installed. That way everything should be build and installed in the normal workflow. 

But I'm not a knowledgeable person when it comes to cmake, so this should definitely be confirmed by someone who is...

**Comment by webbnh** [comment] 2018-11-30 16:38
@marcomagdy, I'm not a CMake expert either, but I share the understandings of @whiplash86 and  @silcowitz:  you can either have the `aws-c-*` stuff as external dependencies, or you can build it as a subproject.  Unfortunately, it appears that the `aws-sdk-cpp` build is trying to get the best of both worlds and falling into the cracks in between.

My project uses a mixture of these approaches:  some of our dependencies are external, and our documentation stipulates that the user must install them first (we assume that they will be installed into the "normal" places, so we don't go to the step of using `find_packages()` to find them); the others are maintained as Git "submodules" and they get pulled when our sources are cloned and built when our sources are built.  Now, in our case, the dependencies are built _into_ our binaries, so there is no question of how to install them, which is not, I think, your situation, but this was just for our convenience -- I'm pretty sure that there are solutions for this, as well (e.g., I wouldn't be surprised if `make install` would install the dependencies as well, if their respective configurations are set up for it...of course, if someone wants the dependencies installed _differently_ from the rest of it, that might be a problem, but, for that corner case, I'd suggest installing them separately instead of using the main build for that).

**Comment by alnr** [comment] 2018-12-13 20:16
+1 for this issue. The solution @whiplash86 suggested seems reasonable (dependencies as submodules by default, search system only if manually specified).

As a workaround, specifying `-DCMAKE_INSTALL_PREFIX` did the trick. You have to be root during the cmake configure step though.

**Comment by singku** [comment] 2019-01-18 00:16
I think it's better to package them as separate packages.

**Closed by singku** 2019-01-18 00:16 UTC
Labels: question

**Comment by glaubitz** [comment] 2019-01-24 11:12
Are those dependencies currently used outside the SDK?
