### ISSUE TITLE
Two tests fail during build on Ubuntu.

### ISSUE THREAD

**Issue by jplflyer** [aws/aws-sdk-cpp#1601] opened 2021-03-24 17:02 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Building as follows:

mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="ecr"
make

I get two build failures:

[----------] Global test environment tear-down
[==========] 387 tests from 68 test cases ran. (4722 ms total)
[  PASSED  ] 385 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] HttpClientTest.TestRandomURLWithProxyAndOtherDeclaredAsNonProxyHost
[  FAILED  ] HttpClientTest.TestRandomURLWithProxy

Scrolling up, they seem to both be the same problem:

[ RUN      ] HttpClientTest.TestRandomURLWithProxyAndOtherDeclaredAsNonProxyHost
/home/jpl/aws-sdk-cpp/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:40: Failure
Failed
The curl error code has to be 28 in [curlCode: 7, Couldn't connect to server]
[  FAILED  ] HttpClientTest.TestRandomURLWithProxyAndOtherDeclaredAsNonProxyHost (5 ms)
...
[ RUN      ] HttpClientTest.TestRandomURLWithProxy
/home/jpl/aws-sdk-cpp/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:40: Failure
Failed
The curl error code has to be 28 in [curlCode: 7, Couldn't connect to server]
[  FAILED  ] HttpClientTest.TestRandomURLWithProxy (4 ms)

**SDK version number**

**Platform/OS/Hardware/Device**
Ubuntu 18.04 LTS instance inside Docker.

**To Reproduce (observed behavior)**
See build steps above.

**Expected behavior**
Expect a clean build.

**Additional context**
At this point I'm trying to figure out how to turn off tests.

**Comment by jplflyer** [comment] 2021-03-24 17:20
This fails on the master branch or if I "git checkout 1.8.167" but is fine if I "git checkout 1.8.145", which is from mid-February.

**Comment by aculnaig** [comment] 2021-03-25 12:18
@jplflyer I've found the flags below for turning off the tests in the `CMakeLists.txt` file

`-DENABLE_TESTING=OFF -DAUTORUN_UNIT_TESTS=OFF -DENABLE_HTTP_CLIENT_TESTING=OFF`

**Comment by sdavtaker** [comment] 2021-03-29 18:58
Hi, 
Thanks for reporting.
I created a clean 18.4 Ubuntu instance in EC2 and build the SDK following your instructions, but I couldn't reproduce.
For the build I installed libssl, libcurl and zlib that were available in apt-get. 
The errors seem related to interactions with Curl, can you check what version of Curl you using? I got 4.5.0, I want to see if there is a specific version I need for it to reproduce?

**Comment by jplflyer** [comment] 2021-03-29 19:15
I'll see if I can create a Dockerfile with just enough to reproduce it.

**Comment by jplflyer** [comment] 2021-03-29 20:01
Okay, I have a repo on GitHub:

https://github.com/jplflyer/FailingAWS

There's a README, a Dockerfile, and a Makefile. Directions in the README, but it's a matter of building the docker image (takes about 10 minutes on my Mac), attaching to the container, then CD-ing into the waiting directory and doing the build process. Everything is in the README.md (hopefully).

**Comment by jplflyer** [comment] 2021-03-29 20:07
And as a reminder, building used to work. If I check out a previous version from mid-February, that builds properly. So it's something new.

**Comment by sdavtaker** [comment] 2021-03-31 15:41
The reason those test didn't fail in previous versions is because they are new, we added support for filtering proxy hosts between those versions. Thanks for sharing the Docker construction. Super useful, I will try it out today and reply with my findings.

**Comment by jplflyer** [comment] 2021-03-31 16:20
Thank you for the explanation. My workaround is working -- I just check out an older version. It'll be interesting to know what I might be doing in my instance that's problematic.

**Comment by sdavtaker** [comment] 2021-03-31 16:51
I was able to reproduce following your steps

**Comment by jplflyer** [comment] 2021-03-31 16:57
There are so many reasons it could be failing for me. It might be a setting in the phusion base image. Maybe I need to use a newer version than the default GCC. Maybe there's a network configuration I'm not doing. Maybe there's just something weird about proxies from Docker containers. But that's a pretty minimal Dockerfile.

Maybe I shouldn't be building from the master branch, and there's a release branch I should use, but I didn't find one.

In any case, I look forward to knowing what the ultimate answer is.

**Comment by sdavtaker** [comment] 2021-03-31 22:04
I tested building like this 

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="ecr"
cmake --build . 
```

and never failed. But when building using make like this

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="ecr"
make -j9
```

It fails the test you mention in the first run, but giving it a retry succeeds the build.

Not sure what it is yet. But it explains how it passed CI at least. It consistently fails make build when triggered by make directly in the first time, but not in the retry, neither when called directly from cmake --build.

**Comment by jplflyer** [comment] 2021-03-31 22:52
I've never been fond of cmake and don't know the implications of what you've discovered so far, although that seems both interesting and weird. Gotta love the weird ones, huh?

**Comment by sdavtaker** [comment] 2021-04-03 23:53
The bug seems very build related, I coudn't reproduce in other platforms, neither using different parameters to call cmake in that particular one, but I got a consistent way to reproduce in the docker you shared. 
So, I gave it a try to see what happens if cmake is upgraded if it is still reproduceable. 
Moving a minor version up (3.10 -> 3.11) makes is unreproducable keeping all things the same. 

This is how I did the upgrade for cmake (couldn't use apt-get since 3.10 is the last released version to 16.04)

```
sudo apt purge cmake
wget https://github.com/Kitware/CMake/releases/download/v3.11.0/cmake-3.11.0-Linux-x86_64.tar.gz
tar -xvf cmake-3.11.0-Linux-x86_64.tar.gz
cd cmake-3.11.0-Linux-x86_64
sudo cp -r bin /usr/
sudo cp -r share /usr/
sudo cp -r doc /usr/share/
sudo cp -r man /usr/share/
```

I hope this helps unblock you. 
I will keep looking into it in case there is more in it to find, but triage seems to indicate its an old sharp edge of cmake we are hitting that was addressed in cmake itself already almost 3 years ago (3.11 is a 2018 version, current one is 3.20).

**Comment by dan-zozo** [comment] 2021-04-06 03:59
I have a similar issue, where I'm building the SDK in a Docker image based off of Ubuntu 20.04.

I bisected the unit-test failing regression to happen somewhere between `1.8.166` and `1.8.167`.

This is my build step:

```
RUN git clone \
        --depth 1 \
        --branch 1.8.166 \
        https://github.com/aws/aws-sdk-cpp.git && \
    cd aws-sdk-cpp && \
    mkdir build && \
    cd build && \
    cmake .. \
        -G Ninja \
        -DBUILD_ONLY="core" \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=OFF \
        -DCUSTOM_MEMORY_MANAGEMENT=OFF \
        -DCMAKE_INSTALL_PREFIX=~/install \
        -DENABLE_UNITY_BUILD=ON && \
    ninja && \
    ninja install && \
    rm -rf /builds/*
```

I did try upgrading CMake to `3.20.0`, but that did not work. The current setup uses CMake `3.16.0`.

I tried invoking `cmake --build .` instead of `ninja`, and it still fails on the same tests.

**Comment by sdavtaker** [comment] 2021-04-26 18:51
Thanks for the added input. I'm looking into improving the CMakeFile definition to better reproduce and control the building. 
I will update when I have more info.

**Comment by ConradMearns** [comment] 2021-05-10 20:39
Switching to 1.8.166 was the only fix that built for me until Friday. I haven't been able to get a build working since.

```Dockerfile
FROM gcc:latest

RUN apt update && \
    apt install -y cmake

RUN git clone https://github.com/aws/aws-sdk-cpp.git  --recurse-submodules && \
    # old fix
    # git checkout 1.8.166 && \
    cd /aws-sdk-cpp

RUN mkdir /opt/AWS-SDK-CPP && \
    cd /opt/AWS-SDK-CPP && \
    cmake /aws-sdk-cpp -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY=s3 && \
    make && make install

ENTRYPOINT ["bash"]
```

All of the errors are from warnings like `/aws-sdk-cpp/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:92:44: error: argument 1 of type 'int16_t[256]' {aka 'short int[256]'} with mismatched bound [-Werror=array-parameter=]` that I can't override. I've tried using `COPY` to overright `compiler_settings.cmake` as described in #787 , have tried reverting cmake and g++ versions , and attempted to set the override `AWS_WARNINGS_ARE_ERRORS` from https://github.com/awslabs/aws-c-common/pull/799 but no luck.

**Comment by sdavtaker** [comment] 2021-05-11 19:21
@ConradMearns I submitted fix for the error you see to aws-c-common https://github.com/awslabs/aws-c-common/pull/797
I'm updating the reference in the submodule.
However, this doesn't solve the other issue related to the SSO segmentation fault on the test mentioned earlier in the thread.

**Comment by sdavtaker** [comment] 2021-05-11 19:43
The error @ConradMearns mentions is a combination of circumstances. GCC added a new warning under the -Wall umbrella, that warning triggered in a line of code in one of the dependencies we build as submodule ```aws-c-common```. In addition, Werror was defined as ON by default in the CMakeLists.txt with no option to turn easily off. Same error occurs when clang12 is used. We are revisiting all our packages cmake scripts to make werror easy to opt-in/out as a building flag and prevent recurrence.

**Comment by sdavtaker** [comment] 2021-05-13 22:49
Hi, 
Update on the broken tests. The test line checking what requests where captured by the httpmocker is trying to read the "back" of an empty vector. 
I'm adding assertion to check that never happens in the mocker and reviewing all the test suite to check we don't hit the same issue in any other place. 
I will keep updating.

**Comment by sdavtaker** [comment] 2021-05-27 16:59
The fix was released yesterday for the Raspeberry fail in main branch.
I'm now testing it in the docker provided by @jplflyer  to confirm the fix works in both cases.

**Comment by sdavtaker** [comment] 2021-05-27 17:20
Ubuntu 16 build has another blocking issue when running the tests.
It now fails on the HttpClientTest.TestRandomURLWithProxy test.
I will update after looking into it in more detail.

**Comment by sdavtaker** [comment] 2021-06-07 20:24
Todays release includes the fix the other error. Tested in the provided container.  Build success. 
Thanks @jplflyer for the container reproduction, it was really useful for root-causing both issues.

**Closed by sdavtaker** 2021-06-07 20:24 UTC
Labels: bug

**Comment by jplflyer** [comment] 2021-06-07 21:36
Thank you, @sdavtaker. I have verified it now builds cleanly. Happy to have helped with the container, and ecstatic to have a working build.
