### ISSUE TITLE
Can't cancel the downloading task sometimes

### ISSUE THREAD

**Issue by boyce-xx** [aws/aws-sdk-cpp#818] opened 2018-03-02 05:45 UTC
Hi,
   I want to download a file from AWS with the SDK, and can be cancel the downloading task by the user.
I'm using the code below to download a file:

>  Aws::SDKOptions options;
  options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
  Aws::InitAPI(options);
  ...
  mRequestPtr = transferManager->DownloadFile(bucket.c_str(), imageFile.c_str(),downloadStreamCallback,downloadConfig,fileLocation.c_str());
  mRequestPtr->WaitUntilFinished();
  ...
  Aws::ShutdownAPI(options);

To cancel the downloading:

>   mRequestPtr->Cancel();

Sometimes, it will always block in mRequestPtr->WaitUntilFinished(); after called the cancel operation.

Did you have noticed the issue?

Thanks.

**Comment by wps132230** [comment] 2018-03-02 21:11
Where did you call `mRequestPtr->Cancel()`?
The thread calling `WaitUntilFinished()` will be blocked until download/upload finished, so you could not call `Cancel()` in the same thread.

You can find an example in `TransferTests.cpp`, which may be helpful.
https://github.com/aws/aws-sdk-cpp/blob/3e364fa5505824de2d02162c65925e95903e7f5d/aws-cpp-sdk-transfer-tests/TransferTests.cpp#L1135

**Comment by boyce-xx** [comment] 2018-03-05 10:34
Hi wps132230,

Thanks for your response.
Yes, I called the Cancel function in another thread like this:

>               pthread_t cancelThread;
>               pthread_create(&cancelThread, NULL, OTACancel,NULL);

the mRequestPtr definition as below:

>   std::shared_ptr<Aws::Transfer::TransferHandle> mRequestPtr;

When the download process is closed to 80%, I will go to cancel it. Sometimes it works, sometimes it will be failed and always blocked in the WaitUntilFinished method(I have been waiting for at least 30 minutes), the fail rate is 1/4.

**Comment by wps132230** [comment] 2018-03-05 18:51
Did you try the callback function: `transferManagerConfig.downloadProgressCallback`?
You can define it and it will be triggered every time you download a part.

If you has to use your own implementation, would you mind share your example code with us? It will be helpful to figure out the problem.

**Comment by boyce-xx** [comment] 2018-03-06 00:41
Hi wps132230,

I'm using the SDK V1.4.9. I see it's the newest version.

and I have defined the download callback function, below is my code:

**Comment by singku** [comment] 2018-03-06 00:51
Is that possible for you to get a gdb/debug view of requestPtr when it's hanging?

**Comment by boyce-xx** [comment] 2018-03-06 01:55
Hi singku,

Thanks for your response.
Yes, I am downloading a file which size is more than 100MB, and I will try your find, then update the log to you.

**Comment by boyce-xx** [comment] 2018-03-06 03:07
Hi singku,
 
Firstly, I post my code here:
(1) cancel operation: print log
> printf("cancelDownload:: Will cancel the download operation\n");
>   mRequestPtr->Cancel();

(2) In TransferManager.cpp, print log:

> printf("*********************TransferManager DoDownload before while*********************\n\n");
>     while(queuedPartIter != queuedParts.end())
>     {
>         handle->ChangePartToFailed(queuedPartIter->second);
> printf("*********************TransferManager*********************\n\n");
>         ++queuedPartIter;
>     }
> printf("***
******************TransferManager DoDownload after while*********************\n\n");





Secondly, when I cancel the download, the output is:
```
<AWS DOWNLOAD> Download Progress: 80 Percent 92964852 bytes
---> update download progress to: 80 
socketfd = 72
send content is: ota:upgrade_progress=80

OTACancel thread: detachCode = 0
cancelDownload:: Will cancel the download operation
*********************TransferManager DoDownload before while*********************

*********************TransferManager*********************

*********************TransferManager DoDownload after while*********************

download finished!
---> 1 User Canceled!
send Log----{"DeviceId":"NTNUT_291788530055","MessageId":"612f161f-1868-3632-6418-1b774075156c","LogType":"OTAResult","LogLevel":0,"OldImageVersion":"TEST_20180227-1420","NewImageVersion":"W4.0.15_20180301-0134","LogMessage":"---Check image version successfully and image needs to upgrade!---bucket = nut2otabucket---imageFile = W4.0.15_20180301-0134.zip---start to download image !---User Canceled!---","TimeStamp":"2018/03/06 02:30:01 +0000"}
""---> 2 User Canceled!
```

if blocking happens, the output is:
```
<AWS DOWNLOAD> Download Progress: 85 Percent 98775599 bytes
---> update download progress to: 85 
socketfd = 77
send content is: ota:upgrade_progress=85

OTACancel thread: detachCode = 0
cancelDownload:: Will cancel the download operation
```

**Comment by singku** [comment] 2018-03-06 06:50
That's the expected case.
The hanging is caused by this execution sequence:
1. Main thread calls DownloadFile(), which will spawn thread 1, then calls WaitUntilFinished().
2. Thread 1 creates multi-part download, which will spawn more threads to download parts.
If there are 10 parts and part 1,2..8 started, then part 1,2..8 are in pending status, part 9 and 10 will be in queued status.
3. Now part 1..8 finished and each one will call HandleGetObjectResponse(), since there are still pending parts (9, 10), `if` test at line TrasferManager.cpp:815 will fail, no one is going to update status.
4. Now your thread calls Cancel(). Parts in queued status will be moved to failed status at line TransferManager.cpp:764 by thread 1. 
5. Now no further part is going to call UpdateStatus(). Transfermanager's status will be InProgress and the value of m_cancel is true.

This is not always the case because sometimes when you call Cancel(), the parts are all in pending status, even though they haven't finish downloading.

 I'll push out the fix ASAP.

**Comment by boyce-xx** [comment] 2018-03-06 08:55
Hi @singku 

Thanks a lot for your clarification in detail.

**Comment by pmogilevskiy** [comment] 2018-03-14 21:31
Hi @singku,

Looking forward to check your fix, We have the same issue.

**Comment by singku** [comment] 2018-03-29 22:50
@pmogilevskiy and @boyce-xx, this has been fixed in https://github.com/aws/aws-sdk-cpp/commit/d45e1c32fcaf391ad47870bcc1ac990f7eb4c252.
Please let us know if you still have problem after using the latest SDK.

**Closed** 2018-03-29 22:50 UTC
Labels: bug

**Comment by boyce-xx** [comment] 2018-04-09 03:05
Hi @singku ,
Sorry for the delay response.
I have tried it, I was not encountered the hang issue with that fix, thank you for your support.
But the waiting time of cancellation operation is too long, sometimes it took 5 minutes or more. Did it have a chance to reduce the waiting time?
