### ISSUE TITLE
JsonView::GetBool returns wrong value

### ISSUE THREAD

**Issue by JanSiebert** [aws/aws-sdk-cpp#1731] opened 2021-08-10 09:40 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
`Aws::Utils::Json::JsonView::GetBool` does not return the correct value if it has been set with `Aws::Utils::Json::JsonValue::WithBool` before. However, it works as expected if the value is serialized, deserialized and read afterwards.

**SDK version number**
1.8.182

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux 13a2faedf94d 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce (observed behavior)**
The following test case fails:
```
#include <gtest/gtest.h>
#include <aws/core/utils/json/JsonSerializer.h>

TEST(JsonTest, BoolTest) {
  Aws::Utils::Json::JsonValue json;
  json.WithBool("yes", true);
  EXPECT_TRUE(json.View().GetBool("yes")); // ERROR

  Aws::Utils::Json::JsonValue json_parsed(json.View().WriteCompact());
  EXPECT_TRUE(json_parsed.View().GetBool("yes")); // OK
}
```
**Expected behavior**
I expected both test conditions to hold.

**Additional context**
```
bool JsonView::GetBool(const Aws::String& key) const
{
    assert(m_value);
    auto item = cJSON_GetObjectItemCaseSensitive(m_value, key.c_str());
    assert(item);
    return item->valueint != 0;
}
```
While `valueint` indeed is set during parsing [1], it is not used to represent the value (i.e. it is not set when creating a boolean value [2]). cJSON offers `cJSON_IsBool`, `cJSON_IsFalse` and `cJSON_IsTrue`. All these methods only look at the `type` field and not the `valueint` field.

[1] https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp#L1348
[2] https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp#L2423

**Comment by KaibaLopez** [comment] 2021-08-13 17:25
Hi @JanSiebert ,
Thanks for pointing this out, I'm able to reproduce this, we'll look into getting this fixed up.

**Comment by HumamHelfawi** [comment] 2023-11-02 11:08
The problem is till there till now..

**Comment by triton3** [comment] 2024-01-03 17:06
This issue is still present in v1.11

**Comment by jmklix** [comment] 2024-02-09 20:46
Here is the fix: https://github.com/aws/aws-sdk-cpp/pull/2852

**Comment by jmklix** [comment] 2024-02-13 23:52
This is fixed with the linked [PR](https://github.com/aws/aws-sdk-cpp/pull/2852). Please let me know if you have any other problems.

**Closed by jmklix** 2024-02-13 23:52 UTC
Labels: bug, pending-release, p2
