### ISSUE TITLE
How to build in Windows MinGW

### ISSUE THREAD

**Issue by iguffick** [aws/aws-sdk-cpp#1141] opened 2019-05-15 15:12 UTC
I'm trying to build the SDK on Windows 10 Pro 64bit, without much success.
I'm using the MinGW installed with Qt, mingw730_32. CMake is version 3.14.4

I've tried a few different options with CMAKE, but still get errors
cmake .. -DBUILD_ONLY="aws-cpp-sdk-dynamodb" -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DTARGET_ARCH=WINDOWS -DFORCE_SHARED_CRT=ON -DENABLE_TESTING="OFF" -G "MinGW Makefiles"

Output is:
`cmake .. -DBUILD_ONLY="aws-cpp-sdk-dynamodb" -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DTARGET_ARCH=WINDOWS -DFORCE_SHARED_CRT=ON -G "MinGW Makefiles"

-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1")
-- Building AWS libraries as static objects
-- Generating windows build config
-- Building project version: 1.7.103
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/Qt/Tools/mingw730_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw730_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw730_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw730_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/TempGreenbank/aws-sdk-cpp/build/.deps
Scanning dependencies of target AwsChecksums
[  4%] Creating directories for 'AwsChecksums'
[  8%] Performing download step (git clone) for 'AwsChecksums'
Cloning into 'AwsChecksums'...
Note: checking out '41dc36d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 41dc36d Define STATIC_CRT (defaults to OFF) so that users can specify static/dynamic run-time library on Windows
[ 12%] No patch step for 'AwsChecksums'
[ 16%] No update step for 'AwsChecksums'
[ 20%] Performing configure step for 'AwsChecksums'
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/Qt/Tools/mingw730_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw730_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/TempGreenbank/aws-sdk-cpp/build/.deps/build/src/AwsChecksums-build
[ 25%] Performing build step for 'AwsChecksums'
Scanning dependencies of target aws-checksums
[  9%] Building C object CMakeFiles/aws-checksums.dir/source/arm/cpuid_arm.c.obj
[ 18%] Building C object CMakeFiles/aws-checksums.dir/source/cpuid_generic.c.obj
[ 27%] Building C object CMakeFiles/aws-checksums.dir/source/crc.c.obj
[ 36%] Building C object CMakeFiles/aws-checksums.dir/source/crc_jni.c.obj
[ 45%] Building C object CMakeFiles/aws-checksums.dir/source/crc_sw.c.obj
[ 54%] Building C object CMakeFiles/aws-checksums.dir/source/intel/cpuid.c.obj
[ 63%] Building C object CMakeFiles/aws-checksums.dir/source/intel/crc32c_sse42_asm.c.obj
[ 72%] Linking C static library libaws-checksums.a
[ 72%] Built target aws-checksums
Scanning dependencies of target aws-checksums-tests
[ 81%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/crc_test.c.obj
[ 90%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/run_tests.c.obj
[100%] Linking C executable D:\TempGreenbank\aws-sdk-cpp\build\bin\aws-checksums-tests.exe
libaws-checksums.a(cpuid_generic.c.obj):cpuid_generic.c:(.text+0x1b): undefined reference to `aws_checksums_do_cpu_id'
libaws-checksums.a(cpuid_generic.c.obj):cpuid_generic.c:(.text+0x4b): undefined reference to `aws_checksums_do_cpu_id'
libaws-checksums.a(cpuid_generic.c.obj):cpuid_generic.c:(.text+0x7b): undefined reference to `aws_checksums_do_cpu_id'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[5]: *** [CMakeFiles\aws-checksums-tests.dir\build.make:103: D:/TempGreenbank/aws-sdk-cpp/build/bin/aws-checksums-tests.exe] Error 1
mingw32-make.exe[4]: *** [CMakeFiles\Makefile2:72: CMakeFiles/aws-checksums-tests.dir/all] Error 2
mingw32-make.exe[3]: *** [Makefile:140: all] Error 2
mingw32-make.exe[2]: *** [CMakeFiles\AwsChecksums.dir\build.make:112: build/src/AwsChecksums-stamp/AwsChecksums-build] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:72: CMakeFiles/AwsChecksums.dir/all] Error 2
mingw32-make.exe: *** [Makefile:83: all] Error 2
CMake Error at CMakeLists.txt:193 (message):
  Failed to build third-party libraries.

-- Configuring incomplete, errors occurred!
`

I don't think I'm trying to do anything out of the ordinary, I would have thought this compilation path would be well used and tested.
Any ideas?

P.S. libaws-checksums.a has been created in the directory "build\.deps\build\src\AwsChecksums-build" if that helps!

**Comment by marcomagdy** [comment] 2019-05-15 16:24
MinGW is not one of the platforms we test for in our CI. I'll try to reproduce the problem and see what we can do to solve it.
Thanks for reporting the issue.

**Comment by marcomagdy** [comment] 2019-05-15 22:18
I tried MinGW with GCC 8.2.0 from https://nuwen.net/mingw.html on a Windows 7 machine and it built aws-checksums just fine.
I ran into a different problem with a missing header while building aws-c-common (but I'm trying to reproduce the problem you're having). Any chance you can point me to a MinGW with GCC 7.3 installation? or at least build with the MinGW package I linked to and let me know if the **same** error is happening?

**Comment by iguffick** [comment] 2019-05-16 08:02
The MinGW I used is from the install of Qt.

Here's a link to the installer (for Qt), when installing you have to tick to select MinGW as an extra package to install.
[https://www.qt.io/download-qt-installer?hsCtaTracking=9f6a2170-a938-42df-a8e2-a9f0b1d6cdce%7C6cb0de4f-9bb5-4778-ab02-bfb62735f3e5](url)

I also had to add "C:\Qt\Tools\mingw730_32\bin" to the system PATH.

**Comment by iguffick** [comment] 2019-05-17 18:00
Hi marcomagdy,

I've tested on a clean Windows 10 Pro 64-bit machine using the MinGW with GCC 8.2.0 from  [https://nuwen.net/mingw.html] as you suggested.

I've Installed Git-2.21.0-64-bit.exe, cmake-3.14.4-win64-x64.msi and mingw-16.1-without-git.exe from  [https://nuwen.net/mingw.html]

Then in command prompt:
  git clone https://github.com/aws/aws-sdk-cpp
  cd aws-sdk-cpp
  mkdir build
  cd build
  cmake .. -G "MinGW Makefiles"

This built aws-checksums fine, but I also ran into an error with a header file for aws-c-common

See log below:
`-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1")
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating windows build config
-- Building project version: 1.7.105
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/TempGreenbank/aws-sdk-cpp/build/.deps
Scanning dependencies of target AwsChecksums
[  4%] Creating directories for 'AwsChecksums'
[  8%] Performing download step (git clone) for 'AwsChecksums'
Cloning into 'AwsChecksums'...
Note: checking out '41dc36d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 41dc36d Define STATIC_CRT (defaults to OFF) so that users can specify static/dynamic run-time library on Windows
[ 12%] No patch step for 'AwsChecksums'
[ 16%] No update step for 'AwsChecksums'
[ 20%] Performing configure step for 'AwsChecksums'
-- The C compiler identification is GNU 8.2.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/TempGreenbank/aws-sdk-cpp/build/.deps/build/src/AwsChecksums-build
[ 25%] Performing build step for 'AwsChecksums'
Scanning dependencies of target aws-checksums
[  9%] Building C object CMakeFiles/aws-checksums.dir/source/arm/cpuid_arm.c.obj
[ 18%] Building C object CMakeFiles/aws-checksums.dir/source/cpuid_generic.c.obj
[ 27%] Building C object CMakeFiles/aws-checksums.dir/source/crc.c.obj
[ 36%] Building C object CMakeFiles/aws-checksums.dir/source/crc_jni.c.obj
[ 45%] Building C object CMakeFiles/aws-checksums.dir/source/crc_sw.c.obj
[ 54%] Building C object CMakeFiles/aws-checksums.dir/source/intel/cpuid.c.obj
[ 63%] Building C object CMakeFiles/aws-checksums.dir/source/intel/crc32c_sse42_asm.c.obj
D:\TempGreenbank\aws-sdk-cpp\build\.deps\build\src\AwsChecksums\source\intel\crc32c_sse42_asm.c: In function 'aws_checksums_crc32c_hw':
D:\TempGreenbank\aws-sdk-cpp\build\.deps\build\src\AwsChecksums\source\intel\crc32c_sse42_asm.c:327:27: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     int input_alignment = (unsigned long int)input & 0x7;
                           ^
[ 72%] Linking C shared library D:\TempGreenbank\aws-sdk-cpp\build\bin\libaws-checksums.dll
[ 72%] Built target aws-checksums
Scanning dependencies of target aws-checksums-tests
[ 81%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/crc_test.c.obj
[ 90%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/run_tests.c.obj
[100%] Linking C executable D:\TempGreenbank\aws-sdk-cpp\build\bin\aws-checksums-tests.exe
[100%] Built target aws-checksums-tests
[ 29%] Performing install step for 'AwsChecksums'
[ 72%] Built target aws-checksums
[100%] Built target aws-checksums-tests
Install the project...
-- Install configuration: "Release"
-- Installing: D:/TempGreenbank/aws-sdk-cpp/build/.deps/install/include/aws/checksums/crc.h
-- Installing: D:/TempGreenbank/aws-sdk-cpp/build/.deps/install/include/aws/checksums/crc_jni.h
-- Installing: D:/TempGreenbank/aws-sdk-cpp/build/.deps/install/include/aws/checksums/exports.h
-- Installing: D:/TempGreenbank/aws-sdk-cpp/build/.deps/install/lib/libaws-checksums.dll.a
-- Installing: D:/TempGreenbank/aws-sdk-cpp/build/.deps/install/bin/libaws-checksums.dll
-- Installing: D:/TempGreenbank/aws-sdk-cpp/build/.deps/install/lib/aws-checksums/cmake/aws-checksums-targets.cmake
-- Installing: D:/TempGreenbank/aws-sdk-cpp/build/.deps/install/lib/aws-checksums/cmake/aws-checksums-targets-release.cmake
-- Installing: D:/TempGreenbank/aws-sdk-cpp/build/.deps/install/lib/aws-checksums/cmake/aws-checksums-config.cmake
[ 33%] Completed 'AwsChecksums'
[ 33%] Built target AwsChecksums
Scanning dependencies of target AwsCCommon
[ 37%] Creating directories for 'AwsCCommon'
[ 41%] Performing download step (git clone) for 'AwsCCommon'
Cloning into 'AwsCCommon'...
Note: checking out 'ac02e17'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ac02e17 Define STATIC_CRT (defaults to OFF) so that users can specify static/dynamic run-time library.
[ 45%] No patch step for 'AwsCCommon'
[ 50%] No update step for 'AwsCCommon'
[ 54%] Performing configure step for 'AwsCCommon'
-- The C compiler identification is GNU 8.2.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Performing Test HAVE_MAY_I_USE
-- Performing Test HAVE_MAY_I_USE - Failed
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Success
-- Performing Test HAVE_MSVC_CPUIDEX
-- Performing Test HAVE_MSVC_CPUIDEX - Success
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Failed
-- Building SIMD base64 decoder
-- Packaging is only supported on Linux
-- Configuring done
-- Generating done
-- Build files have been written to: D:/TempGreenbank/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build
[ 58%] Performing build step for 'AwsCCommon'
Scanning dependencies of target aws-c-common
[  1%] Building C object CMakeFiles/aws-c-common.dir/source/array_list.c.obj
[  3%] Building C object CMakeFiles/aws-c-common.dir/source/byte_buf.c.obj
In file included from D:/TempGreenbank/aws-sdk-cpp/build/.deps/build/src/AwsCCommon/include/aws/common/byte_buf.h:19,
                 from D:\TempGreenbank\aws-sdk-cpp\build\.deps\build\src\AwsCCommon\source\byte_buf.c:16:
D:/TempGreenbank/aws-sdk-cpp/build/.deps/build/src/AwsCCommon/include/aws/common/byte_order.h:24:14: fatal error: netinet/in.h: No such file or directory
 #    include <netinet/in.h>
              ^~~~~~~~~~~~~~
compilation terminated.
mingw32-make.exe[5]: *** [CMakeFiles\aws-c-common.dir\build.make:77: CMakeFiles/aws-c-common.dir/source/byte_buf.c.obj] Error 1
mingw32-make.exe[4]: *** [CMakeFiles\Makefile2:72: CMakeFiles/aws-c-common.dir/all] Error 2
mingw32-make.exe[3]: *** [Makefile:140: all] Error 2
mingw32-make.exe[2]: *** [CMakeFiles\AwsCCommon.dir\build.make:112: build/src/AwsCCommon-stamp/AwsCCommon-build] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:109: CMakeFiles/AwsCCommon.dir/all] Error 2
mingw32-make.exe: *** [Makefile:83: all] Error 2
CMake Error at CMakeLists.txt:193 (message):
  Failed to build third-party libraries.


-- Configuring incomplete, errors occurred!`

**Comment by marcomagdy** [comment] 2019-05-17 18:59
yeah that's the different error I was referring to that I received. But I just wanted to see if you're able to built aws-checksums with MinGW.
I'll work on getting the header-file error above fixed. It should be simple, GCC does not imply GNU/Linux. 
Thanks for getting back to me.

**Comment by marcomagdy** [comment] 2019-05-20 23:50
I'm getting bizarre errors from gcc 8.2 when trying to compile that C project dependency. Things that are perfectly legal and compile just fine on a vanilla gcc 8.2.

I'll be honest with you, this is starting to sound like a rabbit hole that we have never supported. So, I'm going to revert to an older version of the SDK that did not have those C project dependencies and see if I can build successfully. If I'm getting strange errors as well, then I will not look into this issue any further. If I could however build the SDK successfully, then I'll do my best to patch those C deps.

**Comment by iguffick** [comment] 2019-05-21 08:04
Ok, thanks for looking into it. See what you can do.
I'm guessing that for Windows most people use MSVC and MinGW is the less-trodden path!
Qt can be built using MSVC, I'll have a look at installing the  necessary tools and give that a whirl.
Thanks.
Ian.

**Comment by oturpe** [comment] 2019-08-05 14:04
Greetings!

We am hitting this issue, too, trying to build _aws-sdk-cpp_ on Windows with MinGW. Unfortunately in my case, using the Visual Studio tools is not really an option, since I am trying to add some AWS to an existing, large codebase that is built on MinGW and will continue to be built that way.

Do you have a suggestion for the latest version of the sdk that does not have those C dependencies?

**Comment by KaibaLopez** [comment] 2020-06-23 16:20
Hi, 
Going through the backlog on issues and came across this one...
So we don't officially support mingw, but it should be compatible to build... I'll be closing this issue as I don't think there is any action to be done on it.

Having said that though, if you have more specific problems with this, I'd suggest opening a new issue as it would be much easier to keep track of for us.

**Closed by KaibaLopez** 2020-06-23 16:20 UTC
