### ISSUE TITLE
CreateTempFilePath for Linux may create duplicate pathnames

### ISSUE THREAD

**Issue by yasushi-saito** [aws/aws-sdk-cpp#1192] opened 2019-07-11 11:49 UTC
### What platform/OS are you using?
Linux (Ubuntu 16.04)

### Can you provide a TRACE level log? (sanitize any sensitive information)

I'm using Tensorflow gfile S3 support that comes with AWS EC2 DLAMI, and I'm seeing when I write to multiple files concurrently (one thread per file), the files end up corrupted. I don't have the source code for DLAMI, but the source code for gfile s3 is

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L213

which calls

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp#L262

which creates duplicate pathnames when two threads call it within the same millisecond.

**Comment by KaibaLopez** [comment] 2019-07-11 23:36
Hi @yasushi-saito, there's a couple options I can think of to fix or get around this problem.

The first one, we could change the method to add a generated uuid to the tempfile name to ensure uniqueness from file to file, this may cause some unexpected side effects though.
Another possible solution would be to have a lock to avoid threads using the method at the same time, though at that point I'd argue that the caller could implement that lock with less impact, so I'd rather this be modified on the Tensorflow side.
I'll label this as a feature-request as I don't think it quite qualifies as a bug, and I'll start to look into how big of an impact adding the uuid would have on the sdk.
Feel free to add a PR if you think of a better solution too

**Comment by yasushi-saito** [comment] 2019-07-12 00:30
I created an issue on the TH side already so I hope they will work around the problem somehow. But independently of TF, a tempfile function creating duplicate files in pretty screwy. I hope you implement your first suggestion. Locking doesn't help if multiple processes create a tempfile concurrently

**Comment by mariusae** [comment] 2019-07-15 16:49
I'm not sure how this is not a bug. The contract of a temporary file path is that it (1) should be unique; (2) should not exist before. If these conditions cannot be met, the API should fail.

As it is, it's a dangerous bug.

See for example how [Go does this](https://golang.org/src/io/ioutil/tempfile.go).

**Comment by KaibaLopez** [comment] 2019-07-30 16:39
Hi @yasushi-saito and @mariusae, 
Just as an update, I've created a pull request to append a uuid to the file name, which should fix this issue.
I'll update again and close the issue once the change has been published to our master.

**Comment by KaibaLopez** [comment] 2019-08-05 20:20
Hi, the change has been implemented and published on version 1.7.153.

**Closed by KaibaLopez** 2019-08-05 20:20 UTC
Labels: feature-request
