### ISSUE TITLE
Inaccurate TransferCLient GetProgress

### ISSUE THREAD

**Issue by mmustafa-hp** [aws/aws-sdk-cpp#201] opened 2016-06-03 16:01 UTC
While downloading a large file ~4 GB from S3 using the transfer client and the GetProgress to track, I observe that GetProgress returns 100% before the download is complete.
On a slow network, the gap could be up to 25% off the mark.

The test code might be masking the problem by this statement,
if (thisRequest->IsDone() || (thisRequest->GetProgress() >= progressPercent && progressPercent < 100.0f))

since the progressPercent is passed in as a 100.00f, the second condition in the statement is never True.

**Comment by mattman71** [comment] 2016-07-11 15:32
Can anybody help with this?

Could this be happening because retries are happening, but are not accounted for in the total bytes sent used to calculate the progress?

During the failure scenario, whenever I see "Request failed, now waiting <n> ms before attempting again" in the log, I don't get a RetryCount() that corresponds accurately to how many times that message appeared in the log.

In the most egregious failure scenario, the last filesize downloaded I saw was 1478320128 bytes of a 4533251396 byte source file. In that case, IsDone reported true, and of course GetProgress was at 100, but the file wasn't any good. The release containing a potential fix for that, 0.12.17 is still under test, so I'm not sure if this still happens yet. It was intermittent before.

Usually, without a corrupt/incomplete file scenario such as that, the issue is that GetProgress() reports 100 before IsDone() reports true. This is still happening with 0.12.17.

The failure to account for retry bytes is my best guess of any explanation behind both of these issues. What do you think?

**Comment by JonathanHenson** [comment] 2016-08-29 21:50
This is currently being reviewed internally, but I'd love your thoughts while we're at it:

https://s3.amazonaws.com/aws-sdk-cpp-demos/transferRewrite.diff

Notes:

Deleted TransferClient and everything related to it. Added a simpler interface, TransferManager. TransferHandle is the other half of the control interface which is what the user would use to control their transfers. I added a few utilities to core to support the changes. Largely a generic queue locker, and a std::stream_buf that runs off of a preallocated buffer.

Later I'll be adding parallel downloads (harder to pull off), and directory synchronization, but this has feature parity with the original TransferClient.

Major performance differences:
All stream memory is preallocated (so no more allocation during the transfer)
Threading model is simplified.
No busy waits

Things I'm not happy about:
Mutex heavy
I discovered that we aren't handling Http/Continue correctly on Windows while testing. however, this isn't a regression from the previous code base so I'll add it to the backlog.
For multi-part uploads, we only update the transfer progress for each part because it was too complicated to back out updates if a part fails.

Testing notes:
all unit tests, and integration tests pass.
Uploads saturate the nic (which was my goal)
Downloads, since they aren't in parallel, still need work from a performance standpoint.

**Comment by mattman71** [comment] 2016-08-30 19:11
Pardon my ignorance as a bit of a neophyte still... I'm having trouble applying this patch. I just grabbed a fresh clone, but I'm guessing that "patch does not apply" is happening because I need to be at a specific commit for this to work. Got any clues for a tag or a commit I should checkout so I can apply the patch?

C:\PROG\aws-sdk-cpp>git apply --check ..\transferRewrite.diff
error: patch failed: aws-cpp-sdk-core/include/aws/core/VersionConfig.h:1
error: aws-cpp-sdk-core/include/aws/core/VersionConfig.h: patch does not apply
error: patch failed: aws-cpp-sdk-core/nuget/aws-cpp-sdk-core.autopkg:1
error: aws-cpp-sdk-core/nuget/aws-cpp-sdk-core.autopkg: patch does not apply
error: patch failed: aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp:1
error: aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp: patch does not apply
error: patch failed: aws-cpp-sdk-transfer/source/transfer/UploadFileRequest.cpp:1
error: aws-cpp-sdk-transfer/source/transfer/UploadFileRequest.cpp: patch does not apply

**Comment by JonathanHenson** [comment] 2016-08-31 02:17
That's my fault I've become used to reading raw diffs and didn't think about you wanting to apply it and run it. I'll push up a branch for you to play with later tonight.

**Comment by mattman71** [comment] 2016-08-31 04:39
Haha, well, I was reading the raw diff but got in over my head and didn't necessarily need to run it -- I just wanted to switch to looking at the whole thing in context so I could follow the usage with the tests and jump around through the declarations and definitions to see how the new code would work.

My initial glances looked promising. I am hoping this will resolve some of the other troublesome spots I've been having with GetProgress() not reporting the correct number, my inability to get the total size of the source file being downloaded, and the lack of Cancel. I also thought I saw the seeds in there for multi-part download (which would maybe make resumable download possible) -- couldn't tell if it was implemented yet, but I thought I saw some support infrastructure for it.

Didn't mean for you to go through too much trouble for another branch. I could figure out the patch, but apparently only if the diff were made from a tag or specific commit from master that I could checkout before applying. That would be fine for inspecting this. Whichever is easier.

**Comment by JonathanHenson** [comment] 2016-08-31 04:57
I added a branch TransferRewrite for you to experiment with and give feedback before I push it to master.

**Comment by JonathanHenson** [comment] 2016-10-05 18:17
Closing due to the fact that this code has been removed. Reopen if you still have issues with the new TransferManager interface.

**Closed by JonathanHenson** 2016-10-05 18:17 UTC

**Comment by mmustafa-hp** [comment] 2016-10-05 18:57
we integrated and tested the new code. The accuracy issue is resolved. We did have to add code to throttle since the callback was updating too fast for our need. Perhaps a future enhancement

**Comment by mattman71** [comment] 2016-10-05 19:26
So, I no longer see a method to get progress, but the GetBytesTotalSize() and GetBytesTransferred() both seem reliable now, so I can calculate in my downloadProgressCallback.

Is that the correct way to get progress now? I didn't see any type of progress usage scenario in the tests for a download using the new TransferManager.

**Comment by JonathanHenson** [comment] 2016-10-05 19:36
You will receive a callback during the download each time the progress is updated. From there you can call GetBytesTransferred() and GetbytesTotalSize() to update your UI or user on the progress in real time.

**Comment by JonathanHenson** [comment] 2016-10-05 19:37
There were and we deleted them to speed up the tests. Our GA blog post has a sample.
https://aws.amazon.com/blogs/aws/aws-sdk-for-c-now-ready-for-production-use/
